// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: anilist_detail_cache.sql

package store

import (
	"context"
)

const deleteAnilistDetailCache = `-- name: DeleteAnilistDetailCache :exec
DELETE FROM anilist_detail_cache WHERE anilist_id = ?
`

func (q *Queries) DeleteAnilistDetailCache(ctx context.Context, anilistID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAnilistDetailCache, anilistID)
	return err
}

const getAnilistDetailCache = `-- name: GetAnilistDetailCache :one
SELECT anilist_id, payload, fetched_at FROM anilist_detail_cache WHERE anilist_id = ?
`

func (q *Queries) GetAnilistDetailCache(ctx context.Context, anilistID int64) (AnilistDetailCache, error) {
	row := q.db.QueryRowContext(ctx, getAnilistDetailCache, anilistID)
	var i AnilistDetailCache
	err := row.Scan(&i.AnilistID, &i.Payload, &i.FetchedAt)
	return i, err
}

const upsertAnilistDetailCache = `-- name: UpsertAnilistDetailCache :exec
INSERT INTO anilist_detail_cache (anilist_id, payload, fetched_at)
VALUES (?, ?, ?)
ON CONFLICT (anilist_id) DO UPDATE SET
    payload = excluded.payload,
    fetched_at = excluded.fetched_at
`

type UpsertAnilistDetailCacheParams struct {
	AnilistID int64  `json:"anilist_id"`
	Payload   string `json:"payload"`
	FetchedAt int64  `json:"fetched_at"`
}

func (q *Queries) UpsertAnilistDetailCache(ctx context.Context, arg UpsertAnilistDetailCacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertAnilistDetailCache, arg.AnilistID, arg.Payload, arg.FetchedAt)
	return err
}
