// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: download_clients.sql

package store

import (
	"context"
)

const clearDefaultDownloadClients = `-- name: ClearDefaultDownloadClients :exec
UPDATE download_clients SET is_default = 0
`

// ClearDefaultDownloadClients resets all defaults before setting a new one.
func (q *Queries) ClearDefaultDownloadClients(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearDefaultDownloadClients)
	return err
}

const createDownloadClient = `-- name: CreateDownloadClient :one
INSERT INTO download_clients (
    uuid, kind, name, host, port, username, password, enabled, is_default, settings
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, uuid, kind, name, host, port, username, password, enabled, is_default, settings, added_at
`

type CreateDownloadClientParams struct {
	Uuid      string  `json:"uuid"`
	Kind      string  `json:"kind"`
	Name      string  `json:"name"`
	Host      *string `json:"host"`
	Port      *int64  `json:"port"`
	Username  *string `json:"username"`
	Password  *string `json:"password"`
	Enabled   int64   `json:"enabled"`
	IsDefault int64   `json:"is_default"`
	Settings  *string `json:"settings"`
}

func (q *Queries) CreateDownloadClient(ctx context.Context, arg CreateDownloadClientParams) (DownloadClient, error) {
	row := q.db.QueryRowContext(ctx, createDownloadClient,
		arg.Uuid,
		arg.Kind,
		arg.Name,
		arg.Host,
		arg.Port,
		arg.Username,
		arg.Password,
		arg.Enabled,
		arg.IsDefault,
		arg.Settings,
	)
	var i DownloadClient
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Kind,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.Username,
		&i.Password,
		&i.Enabled,
		&i.IsDefault,
		&i.Settings,
		&i.AddedAt,
	)
	return i, err
}

const deleteDownloadClient = `-- name: DeleteDownloadClient :exec
DELETE FROM download_clients WHERE id = ?
`

func (q *Queries) DeleteDownloadClient(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDownloadClient, id)
	return err
}

const getDefaultDownloadClient = `-- name: GetDefaultDownloadClient :one
SELECT id, uuid, kind, name, host, port, username, password, enabled, is_default, settings, added_at FROM download_clients WHERE is_default = 1 LIMIT 1
`

func (q *Queries) GetDefaultDownloadClient(ctx context.Context) (DownloadClient, error) {
	row := q.db.QueryRowContext(ctx, getDefaultDownloadClient)
	var i DownloadClient
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Kind,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.Username,
		&i.Password,
		&i.Enabled,
		&i.IsDefault,
		&i.Settings,
		&i.AddedAt,
	)
	return i, err
}

const getDownloadClient = `-- name: GetDownloadClient :one
SELECT id, uuid, kind, name, host, port, username, password, enabled, is_default, settings, added_at FROM download_clients WHERE id = ?
`

func (q *Queries) GetDownloadClient(ctx context.Context, id int64) (DownloadClient, error) {
	row := q.db.QueryRowContext(ctx, getDownloadClient, id)
	var i DownloadClient
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Kind,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.Username,
		&i.Password,
		&i.Enabled,
		&i.IsDefault,
		&i.Settings,
		&i.AddedAt,
	)
	return i, err
}

const listDownloadClients = `-- name: ListDownloadClients :many
SELECT id, uuid, kind, name, host, port, username, password, enabled, is_default, settings, added_at FROM download_clients ORDER BY is_default DESC, name ASC
`

func (q *Queries) ListDownloadClients(ctx context.Context) ([]DownloadClient, error) {
	rows, err := q.db.QueryContext(ctx, listDownloadClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DownloadClient
	for rows.Next() {
		var i DownloadClient
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Kind,
			&i.Name,
			&i.Host,
			&i.Port,
			&i.Username,
			&i.Password,
			&i.Enabled,
			&i.IsDefault,
			&i.Settings,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledDownloadClients = `-- name: ListEnabledDownloadClients :many
SELECT id, uuid, kind, name, host, port, username, password, enabled, is_default, settings, added_at FROM download_clients WHERE enabled = 1 ORDER BY is_default DESC, name ASC
`

func (q *Queries) ListEnabledDownloadClients(ctx context.Context) ([]DownloadClient, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledDownloadClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DownloadClient
	for rows.Next() {
		var i DownloadClient
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Kind,
			&i.Name,
			&i.Host,
			&i.Port,
			&i.Username,
			&i.Password,
			&i.Enabled,
			&i.IsDefault,
			&i.Settings,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDefaultDownloadClient = `-- name: SetDefaultDownloadClient :exec
UPDATE download_clients SET is_default = 1 WHERE id = ?
`

func (q *Queries) SetDefaultDownloadClient(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, setDefaultDownloadClient, id)
	return err
}

const updateDownloadClient = `-- name: UpdateDownloadClient :one
UPDATE download_clients SET
    kind = ?, name = ?, host = ?, port = ?, username = ?, password = ?,
    enabled = ?, settings = ?
WHERE id = ?
RETURNING id, uuid, kind, name, host, port, username, password, enabled, is_default, settings, added_at
`

type UpdateDownloadClientParams struct {
	Kind     string  `json:"kind"`
	Name     string  `json:"name"`
	Host     *string `json:"host"`
	Port     *int64  `json:"port"`
	Username *string `json:"username"`
	Password *string `json:"password"`
	Enabled  int64   `json:"enabled"`
	Settings *string `json:"settings"`
	ID       int64   `json:"id"`
}

func (q *Queries) UpdateDownloadClient(ctx context.Context, arg UpdateDownloadClientParams) (DownloadClient, error) {
	row := q.db.QueryRowContext(ctx, updateDownloadClient,
		arg.Kind,
		arg.Name,
		arg.Host,
		arg.Port,
		arg.Username,
		arg.Password,
		arg.Enabled,
		arg.Settings,
		arg.ID,
	)
	var i DownloadClient
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Kind,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.Username,
		&i.Password,
		&i.Enabled,
		&i.IsDefault,
		&i.Settings,
		&i.AddedAt,
	)
	return i, err
}
