// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: encoded_outputs.sql

package store

import (
	"context"
)

const countErroredOutputs = `-- name: CountErroredOutputs :one
SELECT COUNT(*) FROM encoded_outputs WHERE episode_id = ? AND status = 'error'
`

// CountErroredOutputs reports failed outputs for an episode; >0 keeps the original.
func (q *Queries) CountErroredOutputs(ctx context.Context, episodeID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countErroredOutputs, episodeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnarchivedOutputs = `-- name: CountUnarchivedOutputs :one
SELECT COUNT(*) FROM encoded_outputs WHERE episode_id = ? AND status != 'archived'
`

// CountUnarchivedOutputs reports how many of an episode's outputs are not yet
// archived; 0 means the episode is fully archived (cleanup trigger).
func (q *Queries) CountUnarchivedOutputs(ctx context.Context, episodeID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnarchivedOutputs, episodeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEncodedOutput = `-- name: CreateEncodedOutput :one
INSERT INTO encoded_outputs (
    uuid, episode_id, resolution, profile_id, encoded_params_snapshot, status
) VALUES (
    ?, ?, ?, ?, ?, ?
)
RETURNING id, uuid, episode_id, resolution, profile_id, encoded_params_snapshot, status, encoded_path, encoded_size, error_message, encoded_at, added_at, modified_at
`

type CreateEncodedOutputParams struct {
	Uuid                  string  `json:"uuid"`
	EpisodeID             int64   `json:"episode_id"`
	Resolution            int64   `json:"resolution"`
	ProfileID             *int64  `json:"profile_id"`
	EncodedParamsSnapshot *string `json:"encoded_params_snapshot"`
	Status                string  `json:"status"`
}

func (q *Queries) CreateEncodedOutput(ctx context.Context, arg CreateEncodedOutputParams) (EncodedOutput, error) {
	row := q.db.QueryRowContext(ctx, createEncodedOutput,
		arg.Uuid,
		arg.EpisodeID,
		arg.Resolution,
		arg.ProfileID,
		arg.EncodedParamsSnapshot,
		arg.Status,
	)
	var i EncodedOutput
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.EpisodeID,
		&i.Resolution,
		&i.ProfileID,
		&i.EncodedParamsSnapshot,
		&i.Status,
		&i.EncodedPath,
		&i.EncodedSize,
		&i.ErrorMessage,
		&i.EncodedAt,
		&i.AddedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const deleteEncodedOutput = `-- name: DeleteEncodedOutput :exec
DELETE FROM encoded_outputs WHERE id = ?
`

func (q *Queries) DeleteEncodedOutput(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEncodedOutput, id)
	return err
}

const getEncodedOutput = `-- name: GetEncodedOutput :one
SELECT id, uuid, episode_id, resolution, profile_id, encoded_params_snapshot, status, encoded_path, encoded_size, error_message, encoded_at, added_at, modified_at FROM encoded_outputs WHERE id = ?
`

func (q *Queries) GetEncodedOutput(ctx context.Context, id int64) (EncodedOutput, error) {
	row := q.db.QueryRowContext(ctx, getEncodedOutput, id)
	var i EncodedOutput
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.EpisodeID,
		&i.Resolution,
		&i.ProfileID,
		&i.EncodedParamsSnapshot,
		&i.Status,
		&i.EncodedPath,
		&i.EncodedSize,
		&i.ErrorMessage,
		&i.EncodedAt,
		&i.AddedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const listEncodedOutputsByEpisode = `-- name: ListEncodedOutputsByEpisode :many
SELECT id, uuid, episode_id, resolution, profile_id, encoded_params_snapshot, status, encoded_path, encoded_size, error_message, encoded_at, added_at, modified_at FROM encoded_outputs WHERE episode_id = ? ORDER BY resolution DESC
`

func (q *Queries) ListEncodedOutputsByEpisode(ctx context.Context, episodeID int64) ([]EncodedOutput, error) {
	rows, err := q.db.QueryContext(ctx, listEncodedOutputsByEpisode, episodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EncodedOutput
	for rows.Next() {
		var i EncodedOutput
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.EpisodeID,
			&i.Resolution,
			&i.ProfileID,
			&i.EncodedParamsSnapshot,
			&i.Status,
			&i.EncodedPath,
			&i.EncodedSize,
			&i.ErrorMessage,
			&i.EncodedAt,
			&i.AddedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEncodedOutputsByStatus = `-- name: ListEncodedOutputsByStatus :many
SELECT id, uuid, episode_id, resolution, profile_id, encoded_params_snapshot, status, encoded_path, encoded_size, error_message, encoded_at, added_at, modified_at FROM encoded_outputs WHERE status = ? ORDER BY added_at ASC
`

func (q *Queries) ListEncodedOutputsByStatus(ctx context.Context, status string) ([]EncodedOutput, error) {
	rows, err := q.db.QueryContext(ctx, listEncodedOutputsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EncodedOutput
	for rows.Next() {
		var i EncodedOutput
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.EpisodeID,
			&i.Resolution,
			&i.ProfileID,
			&i.EncodedParamsSnapshot,
			&i.Status,
			&i.EncodedPath,
			&i.EncodedSize,
			&i.ErrorMessage,
			&i.EncodedAt,
			&i.AddedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEncodedOutputArchived = `-- name: MarkEncodedOutputArchived :exec
UPDATE encoded_outputs SET status = 'archived', modified_at = unixepoch() WHERE id = ?
`

func (q *Queries) MarkEncodedOutputArchived(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markEncodedOutputArchived, id)
	return err
}

const markEncodedOutputEncoded = `-- name: MarkEncodedOutputEncoded :exec
UPDATE encoded_outputs SET
    status = 'encoded', encoded_path = ?, encoded_size = ?,
    encoded_at = unixepoch(), modified_at = unixepoch()
WHERE id = ?
`

type MarkEncodedOutputEncodedParams struct {
	EncodedPath *string `json:"encoded_path"`
	EncodedSize *int64  `json:"encoded_size"`
	ID          int64   `json:"id"`
}

func (q *Queries) MarkEncodedOutputEncoded(ctx context.Context, arg MarkEncodedOutputEncodedParams) error {
	_, err := q.db.ExecContext(ctx, markEncodedOutputEncoded, arg.EncodedPath, arg.EncodedSize, arg.ID)
	return err
}

const resetOrphanedEncodedOutputs = `-- name: ResetOrphanedEncodedOutputs :exec
UPDATE encoded_outputs SET status = 'queued', modified_at = unixepoch()
WHERE status IN ('encoding', 'thumbnailing')
`

// Crash recovery: in-flight encode/thumbnail work resets to queued.
func (q *Queries) ResetOrphanedEncodedOutputs(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetOrphanedEncodedOutputs)
	return err
}

const setEncodedOutputError = `-- name: SetEncodedOutputError :exec
UPDATE encoded_outputs SET
    status = 'error', error_message = ?, modified_at = unixepoch()
WHERE id = ?
`

type SetEncodedOutputErrorParams struct {
	ErrorMessage *string `json:"error_message"`
	ID           int64   `json:"id"`
}

func (q *Queries) SetEncodedOutputError(ctx context.Context, arg SetEncodedOutputErrorParams) error {
	_, err := q.db.ExecContext(ctx, setEncodedOutputError, arg.ErrorMessage, arg.ID)
	return err
}

const setEncodedOutputSnapshot = `-- name: SetEncodedOutputSnapshot :exec
UPDATE encoded_outputs SET
    encoded_params_snapshot = ?, modified_at = unixepoch()
WHERE id = ?
`

type SetEncodedOutputSnapshotParams struct {
	EncodedParamsSnapshot *string `json:"encoded_params_snapshot"`
	ID                    int64   `json:"id"`
}

// SetEncodedOutputSnapshot records the resolved x265 args used for an output
// (reproducibility), set once the arg builder has produced them.
func (q *Queries) SetEncodedOutputSnapshot(ctx context.Context, arg SetEncodedOutputSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, setEncodedOutputSnapshot, arg.EncodedParamsSnapshot, arg.ID)
	return err
}

const setEncodedOutputStatus = `-- name: SetEncodedOutputStatus :exec
UPDATE encoded_outputs SET status = ?, modified_at = unixepoch() WHERE id = ?
`

type SetEncodedOutputStatusParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) SetEncodedOutputStatus(ctx context.Context, arg SetEncodedOutputStatusParams) error {
	_, err := q.db.ExecContext(ctx, setEncodedOutputStatus, arg.Status, arg.ID)
	return err
}
