// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: encode_profiles.sql

package store

import (
	"context"
)

const createEncodeProfile = `-- name: CreateEncodeProfile :one
INSERT INTO encode_profiles (
    uuid, name, builtin, parent_id, codec, crf, preset, smartblur,
    deinterlace, deblock, psy_rd, psy_rdoq, aq_strength, aq_mode, scale,
    audio, container, x265_params, output_resolutions
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, uuid, name, builtin, parent_id, codec, crf, preset, smartblur, deinterlace, deblock, psy_rd, psy_rdoq, aq_strength, aq_mode, scale, audio, container, x265_params, output_resolutions, added_at, modified_at
`

type CreateEncodeProfileParams struct {
	Uuid              string   `json:"uuid"`
	Name              string   `json:"name"`
	Builtin           int64    `json:"builtin"`
	ParentID          *int64   `json:"parent_id"`
	Codec             *string  `json:"codec"`
	Crf               *float64 `json:"crf"`
	Preset            *string  `json:"preset"`
	Smartblur         *int64   `json:"smartblur"`
	Deinterlace       *int64   `json:"deinterlace"`
	Deblock           *string  `json:"deblock"`
	PsyRd             *float64 `json:"psy_rd"`
	PsyRdoq           *float64 `json:"psy_rdoq"`
	AqStrength        *float64 `json:"aq_strength"`
	AqMode            *int64   `json:"aq_mode"`
	Scale             *int64   `json:"scale"`
	Audio             *string  `json:"audio"`
	Container         *string  `json:"container"`
	X265Params        *string  `json:"x265_params"`
	OutputResolutions *string  `json:"output_resolutions"`
}

func (q *Queries) CreateEncodeProfile(ctx context.Context, arg CreateEncodeProfileParams) (EncodeProfile, error) {
	row := q.db.QueryRowContext(ctx, createEncodeProfile,
		arg.Uuid,
		arg.Name,
		arg.Builtin,
		arg.ParentID,
		arg.Codec,
		arg.Crf,
		arg.Preset,
		arg.Smartblur,
		arg.Deinterlace,
		arg.Deblock,
		arg.PsyRd,
		arg.PsyRdoq,
		arg.AqStrength,
		arg.AqMode,
		arg.Scale,
		arg.Audio,
		arg.Container,
		arg.X265Params,
		arg.OutputResolutions,
	)
	var i EncodeProfile
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Builtin,
		&i.ParentID,
		&i.Codec,
		&i.Crf,
		&i.Preset,
		&i.Smartblur,
		&i.Deinterlace,
		&i.Deblock,
		&i.PsyRd,
		&i.PsyRdoq,
		&i.AqStrength,
		&i.AqMode,
		&i.Scale,
		&i.Audio,
		&i.Container,
		&i.X265Params,
		&i.OutputResolutions,
		&i.AddedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const deleteEncodeProfile = `-- name: DeleteEncodeProfile :exec
DELETE FROM encode_profiles WHERE id = ? AND builtin = 0
`

func (q *Queries) DeleteEncodeProfile(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEncodeProfile, id)
	return err
}

const getEncodeProfile = `-- name: GetEncodeProfile :one
SELECT id, uuid, name, builtin, parent_id, codec, crf, preset, smartblur, deinterlace, deblock, psy_rd, psy_rdoq, aq_strength, aq_mode, scale, audio, container, x265_params, output_resolutions, added_at, modified_at FROM encode_profiles WHERE id = ?
`

func (q *Queries) GetEncodeProfile(ctx context.Context, id int64) (EncodeProfile, error) {
	row := q.db.QueryRowContext(ctx, getEncodeProfile, id)
	var i EncodeProfile
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Builtin,
		&i.ParentID,
		&i.Codec,
		&i.Crf,
		&i.Preset,
		&i.Smartblur,
		&i.Deinterlace,
		&i.Deblock,
		&i.PsyRd,
		&i.PsyRdoq,
		&i.AqStrength,
		&i.AqMode,
		&i.Scale,
		&i.Audio,
		&i.Container,
		&i.X265Params,
		&i.OutputResolutions,
		&i.AddedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const getEncodeProfileByName = `-- name: GetEncodeProfileByName :one
SELECT id, uuid, name, builtin, parent_id, codec, crf, preset, smartblur, deinterlace, deblock, psy_rd, psy_rdoq, aq_strength, aq_mode, scale, audio, container, x265_params, output_resolutions, added_at, modified_at FROM encode_profiles WHERE name = ?
`

func (q *Queries) GetEncodeProfileByName(ctx context.Context, name string) (EncodeProfile, error) {
	row := q.db.QueryRowContext(ctx, getEncodeProfileByName, name)
	var i EncodeProfile
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Builtin,
		&i.ParentID,
		&i.Codec,
		&i.Crf,
		&i.Preset,
		&i.Smartblur,
		&i.Deinterlace,
		&i.Deblock,
		&i.PsyRd,
		&i.PsyRdoq,
		&i.AqStrength,
		&i.AqMode,
		&i.Scale,
		&i.Audio,
		&i.Container,
		&i.X265Params,
		&i.OutputResolutions,
		&i.AddedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const getEncodeProfileByUUID = `-- name: GetEncodeProfileByUUID :one
SELECT id, uuid, name, builtin, parent_id, codec, crf, preset, smartblur, deinterlace, deblock, psy_rd, psy_rdoq, aq_strength, aq_mode, scale, audio, container, x265_params, output_resolutions, added_at, modified_at FROM encode_profiles WHERE uuid = ?
`

func (q *Queries) GetEncodeProfileByUUID(ctx context.Context, uuid string) (EncodeProfile, error) {
	row := q.db.QueryRowContext(ctx, getEncodeProfileByUUID, uuid)
	var i EncodeProfile
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Builtin,
		&i.ParentID,
		&i.Codec,
		&i.Crf,
		&i.Preset,
		&i.Smartblur,
		&i.Deinterlace,
		&i.Deblock,
		&i.PsyRd,
		&i.PsyRdoq,
		&i.AqStrength,
		&i.AqMode,
		&i.Scale,
		&i.Audio,
		&i.Container,
		&i.X265Params,
		&i.OutputResolutions,
		&i.AddedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const listBuiltinEncodeProfiles = `-- name: ListBuiltinEncodeProfiles :many
SELECT id, uuid, name, builtin, parent_id, codec, crf, preset, smartblur, deinterlace, deblock, psy_rd, psy_rdoq, aq_strength, aq_mode, scale, audio, container, x265_params, output_resolutions, added_at, modified_at FROM encode_profiles WHERE builtin = 1 ORDER BY name ASC
`

func (q *Queries) ListBuiltinEncodeProfiles(ctx context.Context) ([]EncodeProfile, error) {
	rows, err := q.db.QueryContext(ctx, listBuiltinEncodeProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EncodeProfile
	for rows.Next() {
		var i EncodeProfile
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Builtin,
			&i.ParentID,
			&i.Codec,
			&i.Crf,
			&i.Preset,
			&i.Smartblur,
			&i.Deinterlace,
			&i.Deblock,
			&i.PsyRd,
			&i.PsyRdoq,
			&i.AqStrength,
			&i.AqMode,
			&i.Scale,
			&i.Audio,
			&i.Container,
			&i.X265Params,
			&i.OutputResolutions,
			&i.AddedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEncodeProfiles = `-- name: ListEncodeProfiles :many
SELECT id, uuid, name, builtin, parent_id, codec, crf, preset, smartblur, deinterlace, deblock, psy_rd, psy_rdoq, aq_strength, aq_mode, scale, audio, container, x265_params, output_resolutions, added_at, modified_at FROM encode_profiles ORDER BY builtin DESC, name ASC
`

func (q *Queries) ListEncodeProfiles(ctx context.Context) ([]EncodeProfile, error) {
	rows, err := q.db.QueryContext(ctx, listEncodeProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EncodeProfile
	for rows.Next() {
		var i EncodeProfile
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Builtin,
			&i.ParentID,
			&i.Codec,
			&i.Crf,
			&i.Preset,
			&i.Smartblur,
			&i.Deinterlace,
			&i.Deblock,
			&i.PsyRd,
			&i.PsyRdoq,
			&i.AqStrength,
			&i.AqMode,
			&i.Scale,
			&i.Audio,
			&i.Container,
			&i.X265Params,
			&i.OutputResolutions,
			&i.AddedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveProfileChain = `-- name: ResolveProfileChain :many
WITH RECURSIVE chain(
    id, uuid, name, builtin, parent_id, codec, crf, preset, smartblur,
    deinterlace, deblock, psy_rd, psy_rdoq, aq_strength, aq_mode, scale,
    audio, container, x265_params, output_resolutions, added_at, modified_at, depth
) AS (
    SELECT
        ep.id, ep.uuid, ep.name, ep.builtin, ep.parent_id, ep.codec, ep.crf,
        ep.preset, ep.smartblur, ep.deinterlace, ep.deblock, ep.psy_rd,
        ep.psy_rdoq, ep.aq_strength, ep.aq_mode, ep.scale, ep.audio,
        ep.container, ep.x265_params, ep.output_resolutions, ep.added_at,
        ep.modified_at, 0 AS depth
    FROM encode_profiles ep
    WHERE ep.id = ?
    UNION ALL
    SELECT
        p.id, p.uuid, p.name, p.builtin, p.parent_id, p.codec, p.crf,
        p.preset, p.smartblur, p.deinterlace, p.deblock, p.psy_rd,
        p.psy_rdoq, p.aq_strength, p.aq_mode, p.scale, p.audio,
        p.container, p.x265_params, p.output_resolutions, p.added_at,
        p.modified_at, c.depth + 1
    FROM encode_profiles p
    JOIN chain c ON p.id = c.parent_id
)
SELECT
    id, uuid, name, builtin, parent_id, codec, crf, preset, smartblur,
    deinterlace, deblock, psy_rd, psy_rdoq, aq_strength, aq_mode, scale,
    audio, container, x265_params, output_resolutions, added_at, modified_at
FROM chain ORDER BY depth ASC
`

type ResolveProfileChainRow struct {
	ID                int64    `json:"id"`
	Uuid              string   `json:"uuid"`
	Name              string   `json:"name"`
	Builtin           int64    `json:"builtin"`
	ParentID          *int64   `json:"parent_id"`
	Codec             *string  `json:"codec"`
	Crf               *float64 `json:"crf"`
	Preset            *string  `json:"preset"`
	Smartblur         *int64   `json:"smartblur"`
	Deinterlace       *int64   `json:"deinterlace"`
	Deblock           *string  `json:"deblock"`
	PsyRd             *float64 `json:"psy_rd"`
	PsyRdoq           *float64 `json:"psy_rdoq"`
	AqStrength        *float64 `json:"aq_strength"`
	AqMode            *int64   `json:"aq_mode"`
	Scale             *int64   `json:"scale"`
	Audio             *string  `json:"audio"`
	Container         *string  `json:"container"`
	X265Params        *string  `json:"x265_params"`
	OutputResolutions *string  `json:"output_resolutions"`
	AddedAt           int64    `json:"added_at"`
	ModifiedAt        int64    `json:"modified_at"`
}

// ResolveProfileChain walks parent_id from the given profile to the root,
// ordered child-first; Go COALESCEs each knob field across the chain.
func (q *Queries) ResolveProfileChain(ctx context.Context, id int64) ([]ResolveProfileChainRow, error) {
	rows, err := q.db.QueryContext(ctx, resolveProfileChain, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResolveProfileChainRow
	for rows.Next() {
		var i ResolveProfileChainRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Builtin,
			&i.ParentID,
			&i.Codec,
			&i.Crf,
			&i.Preset,
			&i.Smartblur,
			&i.Deinterlace,
			&i.Deblock,
			&i.PsyRd,
			&i.PsyRdoq,
			&i.AqStrength,
			&i.AqMode,
			&i.Scale,
			&i.Audio,
			&i.Container,
			&i.X265Params,
			&i.OutputResolutions,
			&i.AddedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEncodeProfile = `-- name: UpdateEncodeProfile :one
UPDATE encode_profiles SET
    name = ?, parent_id = ?, codec = ?, crf = ?, preset = ?, smartblur = ?,
    deinterlace = ?, deblock = ?, psy_rd = ?, psy_rdoq = ?, aq_strength = ?,
    aq_mode = ?, scale = ?, audio = ?, container = ?, x265_params = ?,
    output_resolutions = ?, modified_at = unixepoch()
WHERE id = ? AND builtin = 0
RETURNING id, uuid, name, builtin, parent_id, codec, crf, preset, smartblur, deinterlace, deblock, psy_rd, psy_rdoq, aq_strength, aq_mode, scale, audio, container, x265_params, output_resolutions, added_at, modified_at
`

type UpdateEncodeProfileParams struct {
	Name              string   `json:"name"`
	ParentID          *int64   `json:"parent_id"`
	Codec             *string  `json:"codec"`
	Crf               *float64 `json:"crf"`
	Preset            *string  `json:"preset"`
	Smartblur         *int64   `json:"smartblur"`
	Deinterlace       *int64   `json:"deinterlace"`
	Deblock           *string  `json:"deblock"`
	PsyRd             *float64 `json:"psy_rd"`
	PsyRdoq           *float64 `json:"psy_rdoq"`
	AqStrength        *float64 `json:"aq_strength"`
	AqMode            *int64   `json:"aq_mode"`
	Scale             *int64   `json:"scale"`
	Audio             *string  `json:"audio"`
	Container         *string  `json:"container"`
	X265Params        *string  `json:"x265_params"`
	OutputResolutions *string  `json:"output_resolutions"`
	ID                int64    `json:"id"`
}

func (q *Queries) UpdateEncodeProfile(ctx context.Context, arg UpdateEncodeProfileParams) (EncodeProfile, error) {
	row := q.db.QueryRowContext(ctx, updateEncodeProfile,
		arg.Name,
		arg.ParentID,
		arg.Codec,
		arg.Crf,
		arg.Preset,
		arg.Smartblur,
		arg.Deinterlace,
		arg.Deblock,
		arg.PsyRd,
		arg.PsyRdoq,
		arg.AqStrength,
		arg.AqMode,
		arg.Scale,
		arg.Audio,
		arg.Container,
		arg.X265Params,
		arg.OutputResolutions,
		arg.ID,
	)
	var i EncodeProfile
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Builtin,
		&i.ParentID,
		&i.Codec,
		&i.Crf,
		&i.Preset,
		&i.Smartblur,
		&i.Deinterlace,
		&i.Deblock,
		&i.PsyRd,
		&i.PsyRdoq,
		&i.AqStrength,
		&i.AqMode,
		&i.Scale,
		&i.Audio,
		&i.Container,
		&i.X265Params,
		&i.OutputResolutions,
		&i.AddedAt,
		&i.ModifiedAt,
	)
	return i, err
}
