// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: episodes.sql

package store

import (
	"context"
)

const clearEpisodeError = `-- name: ClearEpisodeError :exec
UPDATE episodes SET error_message = NULL, modified_at = unixepoch() WHERE id = ?
`

func (q *Queries) ClearEpisodeError(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, clearEpisodeError, id)
	return err
}

const countEpisodesBySeries = `-- name: CountEpisodesBySeries :one
SELECT COUNT(*) FROM episodes WHERE series_id = ?
`

func (q *Queries) CountEpisodesBySeries(ctx context.Context, seriesID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEpisodesBySeries, seriesID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEpisode = `-- name: CreateEpisode :one
INSERT INTO episodes (
    uuid, series_id, title, episode_no, source_kind, source_url, magnet,
    release_group, resolution, subtype, uncensored, bluray, published_at,
    status, profile_id
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, uuid, series_id, title, episode_no, source_kind, source_url, magnet, release_group, resolution, subtype, uncensored, bluray, published_at, status, source_path, source_size, profile_id, encoded_params_snapshot, downloaded_at, encoded_at, retry_count, error_message, added_at, modified_at, source_cleaned_at
`

type CreateEpisodeParams struct {
	Uuid         string  `json:"uuid"`
	SeriesID     int64   `json:"series_id"`
	Title        *string `json:"title"`
	EpisodeNo    *int64  `json:"episode_no"`
	SourceKind   string  `json:"source_kind"`
	SourceUrl    *string `json:"source_url"`
	Magnet       *string `json:"magnet"`
	ReleaseGroup *string `json:"release_group"`
	Resolution   *int64  `json:"resolution"`
	Subtype      *string `json:"subtype"`
	Uncensored   int64   `json:"uncensored"`
	Bluray       int64   `json:"bluray"`
	PublishedAt  *int64  `json:"published_at"`
	Status       string  `json:"status"`
	ProfileID    *int64  `json:"profile_id"`
}

func (q *Queries) CreateEpisode(ctx context.Context, arg CreateEpisodeParams) (Episode, error) {
	row := q.db.QueryRowContext(ctx, createEpisode,
		arg.Uuid,
		arg.SeriesID,
		arg.Title,
		arg.EpisodeNo,
		arg.SourceKind,
		arg.SourceUrl,
		arg.Magnet,
		arg.ReleaseGroup,
		arg.Resolution,
		arg.Subtype,
		arg.Uncensored,
		arg.Bluray,
		arg.PublishedAt,
		arg.Status,
		arg.ProfileID,
	)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.SeriesID,
		&i.Title,
		&i.EpisodeNo,
		&i.SourceKind,
		&i.SourceUrl,
		&i.Magnet,
		&i.ReleaseGroup,
		&i.Resolution,
		&i.Subtype,
		&i.Uncensored,
		&i.Bluray,
		&i.PublishedAt,
		&i.Status,
		&i.SourcePath,
		&i.SourceSize,
		&i.ProfileID,
		&i.EncodedParamsSnapshot,
		&i.DownloadedAt,
		&i.EncodedAt,
		&i.RetryCount,
		&i.ErrorMessage,
		&i.AddedAt,
		&i.ModifiedAt,
		&i.SourceCleanedAt,
	)
	return i, err
}

const deleteEpisode = `-- name: DeleteEpisode :exec
DELETE FROM episodes WHERE id = ?
`

func (q *Queries) DeleteEpisode(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEpisode, id)
	return err
}

const getEpisode = `-- name: GetEpisode :one
SELECT id, uuid, series_id, title, episode_no, source_kind, source_url, magnet, release_group, resolution, subtype, uncensored, bluray, published_at, status, source_path, source_size, profile_id, encoded_params_snapshot, downloaded_at, encoded_at, retry_count, error_message, added_at, modified_at, source_cleaned_at FROM episodes WHERE id = ?
`

func (q *Queries) GetEpisode(ctx context.Context, id int64) (Episode, error) {
	row := q.db.QueryRowContext(ctx, getEpisode, id)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.SeriesID,
		&i.Title,
		&i.EpisodeNo,
		&i.SourceKind,
		&i.SourceUrl,
		&i.Magnet,
		&i.ReleaseGroup,
		&i.Resolution,
		&i.Subtype,
		&i.Uncensored,
		&i.Bluray,
		&i.PublishedAt,
		&i.Status,
		&i.SourcePath,
		&i.SourceSize,
		&i.ProfileID,
		&i.EncodedParamsSnapshot,
		&i.DownloadedAt,
		&i.EncodedAt,
		&i.RetryCount,
		&i.ErrorMessage,
		&i.AddedAt,
		&i.ModifiedAt,
		&i.SourceCleanedAt,
	)
	return i, err
}

const getEpisodeByUUID = `-- name: GetEpisodeByUUID :one
SELECT id, uuid, series_id, title, episode_no, source_kind, source_url, magnet, release_group, resolution, subtype, uncensored, bluray, published_at, status, source_path, source_size, profile_id, encoded_params_snapshot, downloaded_at, encoded_at, retry_count, error_message, added_at, modified_at, source_cleaned_at FROM episodes WHERE uuid = ?
`

func (q *Queries) GetEpisodeByUUID(ctx context.Context, uuid string) (Episode, error) {
	row := q.db.QueryRowContext(ctx, getEpisodeByUUID, uuid)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.SeriesID,
		&i.Title,
		&i.EpisodeNo,
		&i.SourceKind,
		&i.SourceUrl,
		&i.Magnet,
		&i.ReleaseGroup,
		&i.Resolution,
		&i.Subtype,
		&i.Uncensored,
		&i.Bluray,
		&i.PublishedAt,
		&i.Status,
		&i.SourcePath,
		&i.SourceSize,
		&i.ProfileID,
		&i.EncodedParamsSnapshot,
		&i.DownloadedAt,
		&i.EncodedAt,
		&i.RetryCount,
		&i.ErrorMessage,
		&i.AddedAt,
		&i.ModifiedAt,
		&i.SourceCleanedAt,
	)
	return i, err
}

const getEpisodeWithSeries = `-- name: GetEpisodeWithSeries :one
SELECT episodes.id, episodes.uuid, episodes.series_id, episodes.title, episodes.episode_no, episodes.source_kind, episodes.source_url, episodes.magnet, episodes.release_group, episodes.resolution, episodes.subtype, episodes.uncensored, episodes.bluray, episodes.published_at, episodes.status, episodes.source_path, episodes.source_size, episodes.profile_id, episodes.encoded_params_snapshot, episodes.downloaded_at, episodes.encoded_at, episodes.retry_count, episodes.error_message, episodes.added_at, episodes.modified_at, episodes.source_cleaned_at, series.title AS series_title
FROM episodes
JOIN series ON series.id = episodes.series_id
WHERE episodes.id = ?
`

type GetEpisodeWithSeriesRow struct {
	Episode     Episode `json:"episode"`
	SeriesTitle string  `json:"series_title"`
}

// GetEpisodeWithSeries returns an episode joined with its series title so the
// detail/queue DTOs can show the series name without a second query.
func (q *Queries) GetEpisodeWithSeries(ctx context.Context, id int64) (GetEpisodeWithSeriesRow, error) {
	row := q.db.QueryRowContext(ctx, getEpisodeWithSeries, id)
	var i GetEpisodeWithSeriesRow
	err := row.Scan(
		&i.Episode.ID,
		&i.Episode.Uuid,
		&i.Episode.SeriesID,
		&i.Episode.Title,
		&i.Episode.EpisodeNo,
		&i.Episode.SourceKind,
		&i.Episode.SourceUrl,
		&i.Episode.Magnet,
		&i.Episode.ReleaseGroup,
		&i.Episode.Resolution,
		&i.Episode.Subtype,
		&i.Episode.Uncensored,
		&i.Episode.Bluray,
		&i.Episode.PublishedAt,
		&i.Episode.Status,
		&i.Episode.SourcePath,
		&i.Episode.SourceSize,
		&i.Episode.ProfileID,
		&i.Episode.EncodedParamsSnapshot,
		&i.Episode.DownloadedAt,
		&i.Episode.EncodedAt,
		&i.Episode.RetryCount,
		&i.Episode.ErrorMessage,
		&i.Episode.AddedAt,
		&i.Episode.ModifiedAt,
		&i.Episode.SourceCleanedAt,
		&i.SeriesTitle,
	)
	return i, err
}

const incrementEpisodeRetry = `-- name: IncrementEpisodeRetry :exec
UPDATE episodes SET retry_count = retry_count + 1, modified_at = unixepoch() WHERE id = ?
`

func (q *Queries) IncrementEpisodeRetry(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, incrementEpisodeRetry, id)
	return err
}

const listEpisodesBySeries = `-- name: ListEpisodesBySeries :many
SELECT id, uuid, series_id, title, episode_no, source_kind, source_url, magnet, release_group, resolution, subtype, uncensored, bluray, published_at, status, source_path, source_size, profile_id, encoded_params_snapshot, downloaded_at, encoded_at, retry_count, error_message, added_at, modified_at, source_cleaned_at FROM episodes WHERE series_id = ? ORDER BY episode_no ASC NULLS LAST, added_at ASC
`

func (q *Queries) ListEpisodesBySeries(ctx context.Context, seriesID int64) ([]Episode, error) {
	rows, err := q.db.QueryContext(ctx, listEpisodesBySeries, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Episode
	for rows.Next() {
		var i Episode
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.SeriesID,
			&i.Title,
			&i.EpisodeNo,
			&i.SourceKind,
			&i.SourceUrl,
			&i.Magnet,
			&i.ReleaseGroup,
			&i.Resolution,
			&i.Subtype,
			&i.Uncensored,
			&i.Bluray,
			&i.PublishedAt,
			&i.Status,
			&i.SourcePath,
			&i.SourceSize,
			&i.ProfileID,
			&i.EncodedParamsSnapshot,
			&i.DownloadedAt,
			&i.EncodedAt,
			&i.RetryCount,
			&i.ErrorMessage,
			&i.AddedAt,
			&i.ModifiedAt,
			&i.SourceCleanedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEpisodesByStatus = `-- name: ListEpisodesByStatus :many
SELECT id, uuid, series_id, title, episode_no, source_kind, source_url, magnet, release_group, resolution, subtype, uncensored, bluray, published_at, status, source_path, source_size, profile_id, encoded_params_snapshot, downloaded_at, encoded_at, retry_count, error_message, added_at, modified_at, source_cleaned_at FROM episodes WHERE status = ? ORDER BY added_at ASC
`

func (q *Queries) ListEpisodesByStatus(ctx context.Context, status string) ([]Episode, error) {
	rows, err := q.db.QueryContext(ctx, listEpisodesByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Episode
	for rows.Next() {
		var i Episode
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.SeriesID,
			&i.Title,
			&i.EpisodeNo,
			&i.SourceKind,
			&i.SourceUrl,
			&i.Magnet,
			&i.ReleaseGroup,
			&i.Resolution,
			&i.Subtype,
			&i.Uncensored,
			&i.Bluray,
			&i.PublishedAt,
			&i.Status,
			&i.SourcePath,
			&i.SourceSize,
			&i.ProfileID,
			&i.EncodedParamsSnapshot,
			&i.DownloadedAt,
			&i.EncodedAt,
			&i.RetryCount,
			&i.ErrorMessage,
			&i.AddedAt,
			&i.ModifiedAt,
			&i.SourceCleanedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueuedEpisodes = `-- name: ListQueuedEpisodes :many
SELECT id, uuid, series_id, title, episode_no, source_kind, source_url, magnet, release_group, resolution, subtype, uncensored, bluray, published_at, status, source_path, source_size, profile_id, encoded_params_snapshot, downloaded_at, encoded_at, retry_count, error_message, added_at, modified_at, source_cleaned_at FROM episodes WHERE status = 'queued' ORDER BY added_at ASC
`

func (q *Queries) ListQueuedEpisodes(ctx context.Context) ([]Episode, error) {
	rows, err := q.db.QueryContext(ctx, listQueuedEpisodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Episode
	for rows.Next() {
		var i Episode
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.SeriesID,
			&i.Title,
			&i.EpisodeNo,
			&i.SourceKind,
			&i.SourceUrl,
			&i.Magnet,
			&i.ReleaseGroup,
			&i.Resolution,
			&i.Subtype,
			&i.Uncensored,
			&i.Bluray,
			&i.PublishedAt,
			&i.Status,
			&i.SourcePath,
			&i.SourceSize,
			&i.ProfileID,
			&i.EncodedParamsSnapshot,
			&i.DownloadedAt,
			&i.EncodedAt,
			&i.RetryCount,
			&i.ErrorMessage,
			&i.AddedAt,
			&i.ModifiedAt,
			&i.SourceCleanedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEpisodeArchived = `-- name: MarkEpisodeArchived :exec
UPDATE episodes SET status = 'archived', modified_at = unixepoch() WHERE id = ?
`

func (q *Queries) MarkEpisodeArchived(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markEpisodeArchived, id)
	return err
}

const markEpisodeDownloaded = `-- name: MarkEpisodeDownloaded :exec
UPDATE episodes SET
    status = 'downloaded', source_path = ?, source_size = ?,
    downloaded_at = unixepoch(), modified_at = unixepoch()
WHERE id = ?
`

type MarkEpisodeDownloadedParams struct {
	SourcePath *string `json:"source_path"`
	SourceSize *int64  `json:"source_size"`
	ID         int64   `json:"id"`
}

func (q *Queries) MarkEpisodeDownloaded(ctx context.Context, arg MarkEpisodeDownloadedParams) error {
	_, err := q.db.ExecContext(ctx, markEpisodeDownloaded, arg.SourcePath, arg.SourceSize, arg.ID)
	return err
}

const markEpisodeDownloading = `-- name: MarkEpisodeDownloading :exec
UPDATE episodes SET status = 'downloading', modified_at = unixepoch() WHERE id = ?
`

func (q *Queries) MarkEpisodeDownloading(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markEpisodeDownloading, id)
	return err
}

const markEpisodeEncoded = `-- name: MarkEpisodeEncoded :exec
UPDATE episodes SET
    status = 'encoded', encoded_at = unixepoch(), modified_at = unixepoch()
WHERE id = ?
`

func (q *Queries) MarkEpisodeEncoded(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markEpisodeEncoded, id)
	return err
}

const markEpisodeEncoding = `-- name: MarkEpisodeEncoding :exec
UPDATE episodes SET
    status = 'encoding', encoded_params_snapshot = ?, modified_at = unixepoch()
WHERE id = ?
`

type MarkEpisodeEncodingParams struct {
	EncodedParamsSnapshot *string `json:"encoded_params_snapshot"`
	ID                    int64   `json:"id"`
}

func (q *Queries) MarkEpisodeEncoding(ctx context.Context, arg MarkEpisodeEncodingParams) error {
	_, err := q.db.ExecContext(ctx, markEpisodeEncoding, arg.EncodedParamsSnapshot, arg.ID)
	return err
}

const markEpisodeSourceCleaned = `-- name: MarkEpisodeSourceCleaned :exec
UPDATE episodes SET source_cleaned_at = ?, modified_at = unixepoch() WHERE id = ?
`

type MarkEpisodeSourceCleanedParams struct {
	SourceCleanedAt *int64 `json:"source_cleaned_at"`
	ID              int64  `json:"id"`
}

// MarkEpisodeSourceCleaned stamps the unix time the source files were deleted
// under cleanup_policy=delete, so the UI can show "source cleaned up".
func (q *Queries) MarkEpisodeSourceCleaned(ctx context.Context, arg MarkEpisodeSourceCleanedParams) error {
	_, err := q.db.ExecContext(ctx, markEpisodeSourceCleaned, arg.SourceCleanedAt, arg.ID)
	return err
}

const resetOrphanedDownloadingEpisodes = `-- name: ResetOrphanedDownloadingEpisodes :exec
UPDATE episodes SET status = 'queued', modified_at = unixepoch() WHERE status = 'downloading'
`

// Crash recovery: orphaned in-flight statuses reset to the last durable state.
func (q *Queries) ResetOrphanedDownloadingEpisodes(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetOrphanedDownloadingEpisodes)
	return err
}

const resetOrphanedEncodingEpisodes = `-- name: ResetOrphanedEncodingEpisodes :exec
UPDATE episodes SET status = 'downloaded', modified_at = unixepoch() WHERE status = 'encoding'
`

func (q *Queries) ResetOrphanedEncodingEpisodes(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetOrphanedEncodingEpisodes)
	return err
}

const setEpisodeError = `-- name: SetEpisodeError :exec
UPDATE episodes SET status = 'error', error_message = ?, modified_at = unixepoch() WHERE id = ?
`

type SetEpisodeErrorParams struct {
	ErrorMessage *string `json:"error_message"`
	ID           int64   `json:"id"`
}

func (q *Queries) SetEpisodeError(ctx context.Context, arg SetEpisodeErrorParams) error {
	_, err := q.db.ExecContext(ctx, setEpisodeError, arg.ErrorMessage, arg.ID)
	return err
}

const setEpisodeSourcePath = `-- name: SetEpisodeSourcePath :exec
UPDATE episodes SET source_path = ?, modified_at = unixepoch() WHERE id = ?
`

type SetEpisodeSourcePathParams struct {
	SourcePath *string `json:"source_path"`
	ID         int64   `json:"id"`
}

// SetEpisodeSourcePath updates source_path after the original is moved/cleaned up
// so the row points at the new location (move) or NULL (delete).
func (q *Queries) SetEpisodeSourcePath(ctx context.Context, arg SetEpisodeSourcePathParams) error {
	_, err := q.db.ExecContext(ctx, setEpisodeSourcePath, arg.SourcePath, arg.ID)
	return err
}

const setEpisodeStatus = `-- name: SetEpisodeStatus :exec
UPDATE episodes SET status = ?, modified_at = unixepoch() WHERE id = ?
`

type SetEpisodeStatusParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) SetEpisodeStatus(ctx context.Context, arg SetEpisodeStatusParams) error {
	_, err := q.db.ExecContext(ctx, setEpisodeStatus, arg.Status, arg.ID)
	return err
}
