// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: extensions.sql

package store

import (
	"context"
)

const createExtension = `-- name: CreateExtension :one
INSERT INTO extensions (
    uuid, repo_id, ext_id, name, type, lang, version, source_url,
    payload, enabled, is_builtin, settings, nsfw, icon
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, uuid, repo_id, ext_id, name, type, lang, version, source_url, payload, enabled, is_builtin, settings, nsfw, icon, added_at, modified_at, healthy, health_error, health_checked_at
`

type CreateExtensionParams struct {
	Uuid      string  `json:"uuid"`
	RepoID    *int64  `json:"repo_id"`
	ExtID     string  `json:"ext_id"`
	Name      string  `json:"name"`
	Type      string  `json:"type"`
	Lang      string  `json:"lang"`
	Version   *string `json:"version"`
	SourceUrl *string `json:"source_url"`
	Payload   *string `json:"payload"`
	Enabled   int64   `json:"enabled"`
	IsBuiltin int64   `json:"is_builtin"`
	Settings  *string `json:"settings"`
	Nsfw      int64   `json:"nsfw"`
	Icon      *string `json:"icon"`
}

func (q *Queries) CreateExtension(ctx context.Context, arg CreateExtensionParams) (Extension, error) {
	row := q.db.QueryRowContext(ctx, createExtension,
		arg.Uuid,
		arg.RepoID,
		arg.ExtID,
		arg.Name,
		arg.Type,
		arg.Lang,
		arg.Version,
		arg.SourceUrl,
		arg.Payload,
		arg.Enabled,
		arg.IsBuiltin,
		arg.Settings,
		arg.Nsfw,
		arg.Icon,
	)
	var i Extension
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.RepoID,
		&i.ExtID,
		&i.Name,
		&i.Type,
		&i.Lang,
		&i.Version,
		&i.SourceUrl,
		&i.Payload,
		&i.Enabled,
		&i.IsBuiltin,
		&i.Settings,
		&i.Nsfw,
		&i.Icon,
		&i.AddedAt,
		&i.ModifiedAt,
		&i.Healthy,
		&i.HealthError,
		&i.HealthCheckedAt,
	)
	return i, err
}

const createExtensionRepo = `-- name: CreateExtensionRepo :one
INSERT INTO extension_repos (uuid, name, url, enabled)
VALUES (?, ?, ?, ?)
RETURNING id, uuid, name, url, enabled, last_synced_at, added_at
`

type CreateExtensionRepoParams struct {
	Uuid    string `json:"uuid"`
	Name    string `json:"name"`
	Url     string `json:"url"`
	Enabled int64  `json:"enabled"`
}

func (q *Queries) CreateExtensionRepo(ctx context.Context, arg CreateExtensionRepoParams) (ExtensionRepo, error) {
	row := q.db.QueryRowContext(ctx, createExtensionRepo,
		arg.Uuid,
		arg.Name,
		arg.Url,
		arg.Enabled,
	)
	var i ExtensionRepo
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Url,
		&i.Enabled,
		&i.LastSyncedAt,
		&i.AddedAt,
	)
	return i, err
}

const deleteExtension = `-- name: DeleteExtension :exec
DELETE FROM extensions WHERE id = ? AND is_builtin = 0
`

func (q *Queries) DeleteExtension(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteExtension, id)
	return err
}

const deleteExtensionRepo = `-- name: DeleteExtensionRepo :exec
DELETE FROM extension_repos WHERE id = ?
`

func (q *Queries) DeleteExtensionRepo(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteExtensionRepo, id)
	return err
}

const getExtension = `-- name: GetExtension :one
SELECT id, uuid, repo_id, ext_id, name, type, lang, version, source_url, payload, enabled, is_builtin, settings, nsfw, icon, added_at, modified_at, healthy, health_error, health_checked_at FROM extensions WHERE id = ?
`

func (q *Queries) GetExtension(ctx context.Context, id int64) (Extension, error) {
	row := q.db.QueryRowContext(ctx, getExtension, id)
	var i Extension
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.RepoID,
		&i.ExtID,
		&i.Name,
		&i.Type,
		&i.Lang,
		&i.Version,
		&i.SourceUrl,
		&i.Payload,
		&i.Enabled,
		&i.IsBuiltin,
		&i.Settings,
		&i.Nsfw,
		&i.Icon,
		&i.AddedAt,
		&i.ModifiedAt,
		&i.Healthy,
		&i.HealthError,
		&i.HealthCheckedAt,
	)
	return i, err
}

const getExtensionByExtID = `-- name: GetExtensionByExtID :one
SELECT id, uuid, repo_id, ext_id, name, type, lang, version, source_url, payload, enabled, is_builtin, settings, nsfw, icon, added_at, modified_at, healthy, health_error, health_checked_at FROM extensions WHERE ext_id = ?
`

func (q *Queries) GetExtensionByExtID(ctx context.Context, extID string) (Extension, error) {
	row := q.db.QueryRowContext(ctx, getExtensionByExtID, extID)
	var i Extension
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.RepoID,
		&i.ExtID,
		&i.Name,
		&i.Type,
		&i.Lang,
		&i.Version,
		&i.SourceUrl,
		&i.Payload,
		&i.Enabled,
		&i.IsBuiltin,
		&i.Settings,
		&i.Nsfw,
		&i.Icon,
		&i.AddedAt,
		&i.ModifiedAt,
		&i.Healthy,
		&i.HealthError,
		&i.HealthCheckedAt,
	)
	return i, err
}

const getExtensionRepo = `-- name: GetExtensionRepo :one
SELECT id, uuid, name, url, enabled, last_synced_at, added_at FROM extension_repos WHERE id = ?
`

func (q *Queries) GetExtensionRepo(ctx context.Context, id int64) (ExtensionRepo, error) {
	row := q.db.QueryRowContext(ctx, getExtensionRepo, id)
	var i ExtensionRepo
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Url,
		&i.Enabled,
		&i.LastSyncedAt,
		&i.AddedAt,
	)
	return i, err
}

const getExtensionRepoByURL = `-- name: GetExtensionRepoByURL :one
SELECT id, uuid, name, url, enabled, last_synced_at, added_at FROM extension_repos WHERE url = ?
`

func (q *Queries) GetExtensionRepoByURL(ctx context.Context, url string) (ExtensionRepo, error) {
	row := q.db.QueryRowContext(ctx, getExtensionRepoByURL, url)
	var i ExtensionRepo
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Url,
		&i.Enabled,
		&i.LastSyncedAt,
		&i.AddedAt,
	)
	return i, err
}

const listEnabledExtensionRepos = `-- name: ListEnabledExtensionRepos :many
SELECT id, uuid, name, url, enabled, last_synced_at, added_at FROM extension_repos WHERE enabled = 1 ORDER BY name ASC
`

func (q *Queries) ListEnabledExtensionRepos(ctx context.Context) ([]ExtensionRepo, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledExtensionRepos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExtensionRepo
	for rows.Next() {
		var i ExtensionRepo
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Url,
			&i.Enabled,
			&i.LastSyncedAt,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledExtensionsByType = `-- name: ListEnabledExtensionsByType :many
SELECT id, uuid, repo_id, ext_id, name, type, lang, version, source_url, payload, enabled, is_builtin, settings, nsfw, icon, added_at, modified_at, healthy, health_error, health_checked_at FROM extensions WHERE enabled = 1 AND type = ? ORDER BY name ASC
`

func (q *Queries) ListEnabledExtensionsByType(ctx context.Context, type_ string) ([]Extension, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledExtensionsByType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Extension
	for rows.Next() {
		var i Extension
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.RepoID,
			&i.ExtID,
			&i.Name,
			&i.Type,
			&i.Lang,
			&i.Version,
			&i.SourceUrl,
			&i.Payload,
			&i.Enabled,
			&i.IsBuiltin,
			&i.Settings,
			&i.Nsfw,
			&i.Icon,
			&i.AddedAt,
			&i.ModifiedAt,
			&i.Healthy,
			&i.HealthError,
			&i.HealthCheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExtensionRepos = `-- name: ListExtensionRepos :many
SELECT id, uuid, name, url, enabled, last_synced_at, added_at FROM extension_repos ORDER BY name ASC
`

func (q *Queries) ListExtensionRepos(ctx context.Context) ([]ExtensionRepo, error) {
	rows, err := q.db.QueryContext(ctx, listExtensionRepos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExtensionRepo
	for rows.Next() {
		var i ExtensionRepo
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Url,
			&i.Enabled,
			&i.LastSyncedAt,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExtensions = `-- name: ListExtensions :many
SELECT id, uuid, repo_id, ext_id, name, type, lang, version, source_url, payload, enabled, is_builtin, settings, nsfw, icon, added_at, modified_at, healthy, health_error, health_checked_at FROM extensions ORDER BY name ASC
`

func (q *Queries) ListExtensions(ctx context.Context) ([]Extension, error) {
	rows, err := q.db.QueryContext(ctx, listExtensions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Extension
	for rows.Next() {
		var i Extension
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.RepoID,
			&i.ExtID,
			&i.Name,
			&i.Type,
			&i.Lang,
			&i.Version,
			&i.SourceUrl,
			&i.Payload,
			&i.Enabled,
			&i.IsBuiltin,
			&i.Settings,
			&i.Nsfw,
			&i.Icon,
			&i.AddedAt,
			&i.ModifiedAt,
			&i.Healthy,
			&i.HealthError,
			&i.HealthCheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExtensionsByRepo = `-- name: ListExtensionsByRepo :many
SELECT id, uuid, repo_id, ext_id, name, type, lang, version, source_url, payload, enabled, is_builtin, settings, nsfw, icon, added_at, modified_at, healthy, health_error, health_checked_at FROM extensions WHERE repo_id = ? ORDER BY name ASC
`

func (q *Queries) ListExtensionsByRepo(ctx context.Context, repoID *int64) ([]Extension, error) {
	rows, err := q.db.QueryContext(ctx, listExtensionsByRepo, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Extension
	for rows.Next() {
		var i Extension
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.RepoID,
			&i.ExtID,
			&i.Name,
			&i.Type,
			&i.Lang,
			&i.Version,
			&i.SourceUrl,
			&i.Payload,
			&i.Enabled,
			&i.IsBuiltin,
			&i.Settings,
			&i.Nsfw,
			&i.Icon,
			&i.AddedAt,
			&i.ModifiedAt,
			&i.Healthy,
			&i.HealthError,
			&i.HealthCheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markExtensionRepoSynced = `-- name: MarkExtensionRepoSynced :exec
UPDATE extension_repos SET last_synced_at = unixepoch() WHERE id = ?
`

func (q *Queries) MarkExtensionRepoSynced(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markExtensionRepoSynced, id)
	return err
}

const setExtensionEnabled = `-- name: SetExtensionEnabled :exec
UPDATE extensions SET enabled = ?, modified_at = unixepoch() WHERE id = ?
`

type SetExtensionEnabledParams struct {
	Enabled int64 `json:"enabled"`
	ID      int64 `json:"id"`
}

func (q *Queries) SetExtensionEnabled(ctx context.Context, arg SetExtensionEnabledParams) error {
	_, err := q.db.ExecContext(ctx, setExtensionEnabled, arg.Enabled, arg.ID)
	return err
}

const setExtensionRepoEnabled = `-- name: SetExtensionRepoEnabled :exec
UPDATE extension_repos SET enabled = ? WHERE id = ?
`

type SetExtensionRepoEnabledParams struct {
	Enabled int64 `json:"enabled"`
	ID      int64 `json:"id"`
}

func (q *Queries) SetExtensionRepoEnabled(ctx context.Context, arg SetExtensionRepoEnabledParams) error {
	_, err := q.db.ExecContext(ctx, setExtensionRepoEnabled, arg.Enabled, arg.ID)
	return err
}

const updateExtensionHealth = `-- name: UpdateExtensionHealth :exec
UPDATE extensions
SET healthy = ?, health_error = ?, health_checked_at = COALESCE(?, unixepoch())
WHERE ext_id = ?
`

type UpdateExtensionHealthParams struct {
	Healthy         *int64  `json:"healthy"`
	HealthError     *string `json:"health_error"`
	HealthCheckedAt *int64  `json:"health_checked_at"`
	ExtID           string  `json:"ext_id"`
}

func (q *Queries) UpdateExtensionHealth(ctx context.Context, arg UpdateExtensionHealthParams) error {
	_, err := q.db.ExecContext(ctx, updateExtensionHealth,
		arg.Healthy,
		arg.HealthError,
		arg.HealthCheckedAt,
		arg.ExtID,
	)
	return err
}

const updateExtensionSettings = `-- name: UpdateExtensionSettings :exec
UPDATE extensions SET settings = ?, modified_at = unixepoch() WHERE id = ?
`

type UpdateExtensionSettingsParams struct {
	Settings *string `json:"settings"`
	ID       int64   `json:"id"`
}

func (q *Queries) UpdateExtensionSettings(ctx context.Context, arg UpdateExtensionSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateExtensionSettings, arg.Settings, arg.ID)
	return err
}

const upsertExtensionByExtID = `-- name: UpsertExtensionByExtID :one
INSERT INTO extensions (
    uuid, repo_id, ext_id, name, type, lang, version, source_url,
    payload, enabled, is_builtin, settings, nsfw, icon
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT (ext_id) DO UPDATE SET
    repo_id = excluded.repo_id,
    name = excluded.name,
    type = excluded.type,
    lang = excluded.lang,
    version = excluded.version,
    source_url = excluded.source_url,
    payload = excluded.payload,
    settings = excluded.settings,
    nsfw = excluded.nsfw,
    icon = excluded.icon,
    modified_at = unixepoch()
RETURNING id, uuid, repo_id, ext_id, name, type, lang, version, source_url, payload, enabled, is_builtin, settings, nsfw, icon, added_at, modified_at, healthy, health_error, health_checked_at
`

type UpsertExtensionByExtIDParams struct {
	Uuid      string  `json:"uuid"`
	RepoID    *int64  `json:"repo_id"`
	ExtID     string  `json:"ext_id"`
	Name      string  `json:"name"`
	Type      string  `json:"type"`
	Lang      string  `json:"lang"`
	Version   *string `json:"version"`
	SourceUrl *string `json:"source_url"`
	Payload   *string `json:"payload"`
	Enabled   int64   `json:"enabled"`
	IsBuiltin int64   `json:"is_builtin"`
	Settings  *string `json:"settings"`
	Nsfw      int64   `json:"nsfw"`
	Icon      *string `json:"icon"`
}

func (q *Queries) UpsertExtensionByExtID(ctx context.Context, arg UpsertExtensionByExtIDParams) (Extension, error) {
	row := q.db.QueryRowContext(ctx, upsertExtensionByExtID,
		arg.Uuid,
		arg.RepoID,
		arg.ExtID,
		arg.Name,
		arg.Type,
		arg.Lang,
		arg.Version,
		arg.SourceUrl,
		arg.Payload,
		arg.Enabled,
		arg.IsBuiltin,
		arg.Settings,
		arg.Nsfw,
		arg.Icon,
	)
	var i Extension
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.RepoID,
		&i.ExtID,
		&i.Name,
		&i.Type,
		&i.Lang,
		&i.Version,
		&i.SourceUrl,
		&i.Payload,
		&i.Enabled,
		&i.IsBuiltin,
		&i.Settings,
		&i.Nsfw,
		&i.Icon,
		&i.AddedAt,
		&i.ModifiedAt,
		&i.Healthy,
		&i.HealthError,
		&i.HealthCheckedAt,
	)
	return i, err
}
