// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feeds.sql

package store

import (
	"context"
)

const createFeed = `-- name: CreateFeed :one
INSERT INTO feeds (
    uuid, series_id, type, site, url, quality, subtype, deinterlace,
    uncensored, bluray, title_regex, extra_tags, interval_seconds,
    offset_seconds, seen_cache, enabled
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, uuid, series_id, type, site, url, quality, subtype, deinterlace, uncensored, bluray, title_regex, extra_tags, interval_seconds, offset_seconds, last_checked_at, seen_cache, enabled, error_message, added_at, modified_at
`

type CreateFeedParams struct {
	Uuid            string  `json:"uuid"`
	SeriesID        int64   `json:"series_id"`
	Type            string  `json:"type"`
	Site            *string `json:"site"`
	Url             string  `json:"url"`
	Quality         *int64  `json:"quality"`
	Subtype         *string `json:"subtype"`
	Deinterlace     int64   `json:"deinterlace"`
	Uncensored      int64   `json:"uncensored"`
	Bluray          int64   `json:"bluray"`
	TitleRegex      *string `json:"title_regex"`
	ExtraTags       *string `json:"extra_tags"`
	IntervalSeconds int64   `json:"interval_seconds"`
	OffsetSeconds   int64   `json:"offset_seconds"`
	SeenCache       *string `json:"seen_cache"`
	Enabled         int64   `json:"enabled"`
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, createFeed,
		arg.Uuid,
		arg.SeriesID,
		arg.Type,
		arg.Site,
		arg.Url,
		arg.Quality,
		arg.Subtype,
		arg.Deinterlace,
		arg.Uncensored,
		arg.Bluray,
		arg.TitleRegex,
		arg.ExtraTags,
		arg.IntervalSeconds,
		arg.OffsetSeconds,
		arg.SeenCache,
		arg.Enabled,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.SeriesID,
		&i.Type,
		&i.Site,
		&i.Url,
		&i.Quality,
		&i.Subtype,
		&i.Deinterlace,
		&i.Uncensored,
		&i.Bluray,
		&i.TitleRegex,
		&i.ExtraTags,
		&i.IntervalSeconds,
		&i.OffsetSeconds,
		&i.LastCheckedAt,
		&i.SeenCache,
		&i.Enabled,
		&i.ErrorMessage,
		&i.AddedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const deleteFeed = `-- name: DeleteFeed :exec
DELETE FROM feeds WHERE id = ?
`

func (q *Queries) DeleteFeed(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteFeed, id)
	return err
}

const getFeed = `-- name: GetFeed :one
SELECT id, uuid, series_id, type, site, url, quality, subtype, deinterlace, uncensored, bluray, title_regex, extra_tags, interval_seconds, offset_seconds, last_checked_at, seen_cache, enabled, error_message, added_at, modified_at FROM feeds WHERE id = ?
`

func (q *Queries) GetFeed(ctx context.Context, id int64) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeed, id)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.SeriesID,
		&i.Type,
		&i.Site,
		&i.Url,
		&i.Quality,
		&i.Subtype,
		&i.Deinterlace,
		&i.Uncensored,
		&i.Bluray,
		&i.TitleRegex,
		&i.ExtraTags,
		&i.IntervalSeconds,
		&i.OffsetSeconds,
		&i.LastCheckedAt,
		&i.SeenCache,
		&i.Enabled,
		&i.ErrorMessage,
		&i.AddedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const getFeedByURL = `-- name: GetFeedByURL :one
SELECT id, uuid, series_id, type, site, url, quality, subtype, deinterlace, uncensored, bluray, title_regex, extra_tags, interval_seconds, offset_seconds, last_checked_at, seen_cache, enabled, error_message, added_at, modified_at FROM feeds WHERE url = ?
`

func (q *Queries) GetFeedByURL(ctx context.Context, url string) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeedByURL, url)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.SeriesID,
		&i.Type,
		&i.Site,
		&i.Url,
		&i.Quality,
		&i.Subtype,
		&i.Deinterlace,
		&i.Uncensored,
		&i.Bluray,
		&i.TitleRegex,
		&i.ExtraTags,
		&i.IntervalSeconds,
		&i.OffsetSeconds,
		&i.LastCheckedAt,
		&i.SeenCache,
		&i.Enabled,
		&i.ErrorMessage,
		&i.AddedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const listFeeds = `-- name: ListFeeds :many
SELECT id, uuid, series_id, type, site, url, quality, subtype, deinterlace, uncensored, bluray, title_regex, extra_tags, interval_seconds, offset_seconds, last_checked_at, seen_cache, enabled, error_message, added_at, modified_at FROM feeds ORDER BY added_at ASC
`

func (q *Queries) ListFeeds(ctx context.Context) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, listFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.SeriesID,
			&i.Type,
			&i.Site,
			&i.Url,
			&i.Quality,
			&i.Subtype,
			&i.Deinterlace,
			&i.Uncensored,
			&i.Bluray,
			&i.TitleRegex,
			&i.ExtraTags,
			&i.IntervalSeconds,
			&i.OffsetSeconds,
			&i.LastCheckedAt,
			&i.SeenCache,
			&i.Enabled,
			&i.ErrorMessage,
			&i.AddedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedsBySeries = `-- name: ListFeedsBySeries :many
SELECT id, uuid, series_id, type, site, url, quality, subtype, deinterlace, uncensored, bluray, title_regex, extra_tags, interval_seconds, offset_seconds, last_checked_at, seen_cache, enabled, error_message, added_at, modified_at FROM feeds WHERE series_id = ? ORDER BY added_at ASC
`

func (q *Queries) ListFeedsBySeries(ctx context.Context, seriesID int64) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, listFeedsBySeries, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.SeriesID,
			&i.Type,
			&i.Site,
			&i.Url,
			&i.Quality,
			&i.Subtype,
			&i.Deinterlace,
			&i.Uncensored,
			&i.Bluray,
			&i.TitleRegex,
			&i.ExtraTags,
			&i.IntervalSeconds,
			&i.OffsetSeconds,
			&i.LastCheckedAt,
			&i.SeenCache,
			&i.Enabled,
			&i.ErrorMessage,
			&i.AddedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedsDueForPoll = `-- name: ListFeedsDueForPoll :many
SELECT f.id, f.uuid, f.series_id, f.type, f.site, f.url, f.quality, f.subtype, f.deinterlace, f.uncensored, f.bluray, f.title_regex, f.extra_tags, f.interval_seconds, f.offset_seconds, f.last_checked_at, f.seen_cache, f.enabled, f.error_message, f.added_at, f.modified_at
FROM feeds f
JOIN series s ON s.id = f.series_id
WHERE f.enabled = 1
  AND s.subscribed = 1
  AND s.user_status IS NULL
  AND (s.airing_status IS NULL OR s.airing_status NOT IN ('CANCELLED', 'NOT_YET_RELEASED'))
  AND (
        f.last_checked_at IS NULL
     OR f.last_checked_at + f.interval_seconds <= ?1
  )
ORDER BY f.last_checked_at ASC NULLS FIRST
`

// ListFeedsDueForPoll returns enabled feeds whose series is subscribed, has no
// manual status override (user_status IS NULL - Paused/Dropped series are skipped
// so background automation never overrides a manual choice), and whose derived
// status still permits polling (not completed/cancelled/not_aired), and whose
// interval has elapsed. The completed/up_to_date split is computed in Go from
// airing_status + archive counts; this query enforces the cheap, durable filters.
func (q *Queries) ListFeedsDueForPoll(ctx context.Context, now *int64) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, listFeedsDueForPoll, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.SeriesID,
			&i.Type,
			&i.Site,
			&i.Url,
			&i.Quality,
			&i.Subtype,
			&i.Deinterlace,
			&i.Uncensored,
			&i.Bluray,
			&i.TitleRegex,
			&i.ExtraTags,
			&i.IntervalSeconds,
			&i.OffsetSeconds,
			&i.LastCheckedAt,
			&i.SeenCache,
			&i.Enabled,
			&i.ErrorMessage,
			&i.AddedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markFeedChecked = `-- name: MarkFeedChecked :exec
UPDATE feeds SET
    last_checked_at = ?1, seen_cache = ?2,
    error_message = NULL, modified_at = unixepoch()
WHERE id = ?3
`

type MarkFeedCheckedParams struct {
	Now       *int64  `json:"now"`
	SeenCache *string `json:"seen_cache"`
	ID        int64   `json:"id"`
}

func (q *Queries) MarkFeedChecked(ctx context.Context, arg MarkFeedCheckedParams) error {
	_, err := q.db.ExecContext(ctx, markFeedChecked, arg.Now, arg.SeenCache, arg.ID)
	return err
}

const markFeedError = `-- name: MarkFeedError :exec
UPDATE feeds SET
    last_checked_at = ?1, error_message = ?2,
    modified_at = unixepoch()
WHERE id = ?3
`

type MarkFeedErrorParams struct {
	Now          *int64  `json:"now"`
	ErrorMessage *string `json:"error_message"`
	ID           int64   `json:"id"`
}

func (q *Queries) MarkFeedError(ctx context.Context, arg MarkFeedErrorParams) error {
	_, err := q.db.ExecContext(ctx, markFeedError, arg.Now, arg.ErrorMessage, arg.ID)
	return err
}

const setFeedEnabled = `-- name: SetFeedEnabled :exec
UPDATE feeds SET enabled = ?, modified_at = unixepoch() WHERE id = ?
`

type SetFeedEnabledParams struct {
	Enabled int64 `json:"enabled"`
	ID      int64 `json:"id"`
}

func (q *Queries) SetFeedEnabled(ctx context.Context, arg SetFeedEnabledParams) error {
	_, err := q.db.ExecContext(ctx, setFeedEnabled, arg.Enabled, arg.ID)
	return err
}

const updateFeed = `-- name: UpdateFeed :one
UPDATE feeds SET
    type = ?, site = ?, url = ?, quality = ?, subtype = ?, deinterlace = ?,
    uncensored = ?, bluray = ?, title_regex = ?, extra_tags = ?,
    interval_seconds = ?, offset_seconds = ?, enabled = ?, modified_at = unixepoch()
WHERE id = ?
RETURNING id, uuid, series_id, type, site, url, quality, subtype, deinterlace, uncensored, bluray, title_regex, extra_tags, interval_seconds, offset_seconds, last_checked_at, seen_cache, enabled, error_message, added_at, modified_at
`

type UpdateFeedParams struct {
	Type            string  `json:"type"`
	Site            *string `json:"site"`
	Url             string  `json:"url"`
	Quality         *int64  `json:"quality"`
	Subtype         *string `json:"subtype"`
	Deinterlace     int64   `json:"deinterlace"`
	Uncensored      int64   `json:"uncensored"`
	Bluray          int64   `json:"bluray"`
	TitleRegex      *string `json:"title_regex"`
	ExtraTags       *string `json:"extra_tags"`
	IntervalSeconds int64   `json:"interval_seconds"`
	OffsetSeconds   int64   `json:"offset_seconds"`
	Enabled         int64   `json:"enabled"`
	ID              int64   `json:"id"`
}

func (q *Queries) UpdateFeed(ctx context.Context, arg UpdateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, updateFeed,
		arg.Type,
		arg.Site,
		arg.Url,
		arg.Quality,
		arg.Subtype,
		arg.Deinterlace,
		arg.Uncensored,
		arg.Bluray,
		arg.TitleRegex,
		arg.ExtraTags,
		arg.IntervalSeconds,
		arg.OffsetSeconds,
		arg.Enabled,
		arg.ID,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.SeriesID,
		&i.Type,
		&i.Site,
		&i.Url,
		&i.Quality,
		&i.Subtype,
		&i.Deinterlace,
		&i.Uncensored,
		&i.Bluray,
		&i.TitleRegex,
		&i.ExtraTags,
		&i.IntervalSeconds,
		&i.OffsetSeconds,
		&i.LastCheckedAt,
		&i.SeenCache,
		&i.Enabled,
		&i.ErrorMessage,
		&i.AddedAt,
		&i.ModifiedAt,
	)
	return i, err
}
