// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

type AnilistDetailCache struct {
	AnilistID int64  `json:"anilist_id"`
	Payload   string `json:"payload"`
	FetchedAt int64  `json:"fetched_at"`
}

type DownloadClient struct {
	ID        int64   `json:"id"`
	Uuid      string  `json:"uuid"`
	Kind      string  `json:"kind"`
	Name      string  `json:"name"`
	Host      *string `json:"host"`
	Port      *int64  `json:"port"`
	Username  *string `json:"username"`
	Password  *string `json:"password"`
	Enabled   int64   `json:"enabled"`
	IsDefault int64   `json:"is_default"`
	Settings  *string `json:"settings"`
	AddedAt   int64   `json:"added_at"`
}

type EncodeProfile struct {
	ID                int64    `json:"id"`
	Uuid              string   `json:"uuid"`
	Name              string   `json:"name"`
	Builtin           int64    `json:"builtin"`
	ParentID          *int64   `json:"parent_id"`
	Codec             *string  `json:"codec"`
	Crf               *float64 `json:"crf"`
	Preset            *string  `json:"preset"`
	Smartblur         *int64   `json:"smartblur"`
	Deinterlace       *int64   `json:"deinterlace"`
	Deblock           *string  `json:"deblock"`
	PsyRd             *float64 `json:"psy_rd"`
	PsyRdoq           *float64 `json:"psy_rdoq"`
	AqStrength        *float64 `json:"aq_strength"`
	AqMode            *int64   `json:"aq_mode"`
	Scale             *int64   `json:"scale"`
	Audio             *string  `json:"audio"`
	Container         *string  `json:"container"`
	X265Params        *string  `json:"x265_params"`
	OutputResolutions *string  `json:"output_resolutions"`
	AddedAt           int64    `json:"added_at"`
	ModifiedAt        int64    `json:"modified_at"`
}

type EncodedOutput struct {
	ID                    int64   `json:"id"`
	Uuid                  string  `json:"uuid"`
	EpisodeID             int64   `json:"episode_id"`
	Resolution            int64   `json:"resolution"`
	ProfileID             *int64  `json:"profile_id"`
	EncodedParamsSnapshot *string `json:"encoded_params_snapshot"`
	Status                string  `json:"status"`
	EncodedPath           *string `json:"encoded_path"`
	EncodedSize           *int64  `json:"encoded_size"`
	ErrorMessage          *string `json:"error_message"`
	EncodedAt             *int64  `json:"encoded_at"`
	AddedAt               int64   `json:"added_at"`
	ModifiedAt            int64   `json:"modified_at"`
}

type Episode struct {
	ID                    int64   `json:"id"`
	Uuid                  string  `json:"uuid"`
	SeriesID              int64   `json:"series_id"`
	Title                 *string `json:"title"`
	EpisodeNo             *int64  `json:"episode_no"`
	SourceKind            string  `json:"source_kind"`
	SourceUrl             *string `json:"source_url"`
	Magnet                *string `json:"magnet"`
	ReleaseGroup          *string `json:"release_group"`
	Resolution            *int64  `json:"resolution"`
	Subtype               *string `json:"subtype"`
	Uncensored            int64   `json:"uncensored"`
	Bluray                int64   `json:"bluray"`
	PublishedAt           *int64  `json:"published_at"`
	Status                string  `json:"status"`
	SourcePath            *string `json:"source_path"`
	SourceSize            *int64  `json:"source_size"`
	ProfileID             *int64  `json:"profile_id"`
	EncodedParamsSnapshot *string `json:"encoded_params_snapshot"`
	DownloadedAt          *int64  `json:"downloaded_at"`
	EncodedAt             *int64  `json:"encoded_at"`
	RetryCount            int64   `json:"retry_count"`
	ErrorMessage          *string `json:"error_message"`
	AddedAt               int64   `json:"added_at"`
	ModifiedAt            int64   `json:"modified_at"`
	SourceCleanedAt       *int64  `json:"source_cleaned_at"`
}

type Extension struct {
	ID         int64   `json:"id"`
	Uuid       string  `json:"uuid"`
	RepoID     *int64  `json:"repo_id"`
	ExtID      string  `json:"ext_id"`
	Name       string  `json:"name"`
	Type       string  `json:"type"`
	Lang       string  `json:"lang"`
	Version    *string `json:"version"`
	SourceUrl  *string `json:"source_url"`
	Payload    *string `json:"payload"`
	Enabled    int64   `json:"enabled"`
	IsBuiltin  int64   `json:"is_builtin"`
	Settings   *string `json:"settings"`
	Nsfw       int64   `json:"nsfw"`
	Icon       *string `json:"icon"`
	AddedAt    int64   `json:"added_at"`
	ModifiedAt int64   `json:"modified_at"`
}

type ExtensionRepo struct {
	ID           int64  `json:"id"`
	Uuid         string `json:"uuid"`
	Name         string `json:"name"`
	Url          string `json:"url"`
	Enabled      int64  `json:"enabled"`
	LastSyncedAt *int64 `json:"last_synced_at"`
	AddedAt      int64  `json:"added_at"`
}

type Feed struct {
	ID              int64   `json:"id"`
	Uuid            string  `json:"uuid"`
	SeriesID        int64   `json:"series_id"`
	Type            string  `json:"type"`
	Site            *string `json:"site"`
	Url             string  `json:"url"`
	Quality         *int64  `json:"quality"`
	Subtype         *string `json:"subtype"`
	Deinterlace     int64   `json:"deinterlace"`
	Uncensored      int64   `json:"uncensored"`
	Bluray          int64   `json:"bluray"`
	TitleRegex      *string `json:"title_regex"`
	ExtraTags       *string `json:"extra_tags"`
	IntervalSeconds int64   `json:"interval_seconds"`
	OffsetSeconds   int64   `json:"offset_seconds"`
	LastCheckedAt   *int64  `json:"last_checked_at"`
	SeenCache       *string `json:"seen_cache"`
	Enabled         int64   `json:"enabled"`
	ErrorMessage    *string `json:"error_message"`
	AddedAt         int64   `json:"added_at"`
	ModifiedAt      int64   `json:"modified_at"`
}

type Screenshot struct {
	ID        int64   `json:"id"`
	Uuid      string  `json:"uuid"`
	EpisodeID int64   `json:"episode_id"`
	SeriesID  int64   `json:"series_id"`
	Path      string  `json:"path"`
	Caption   *string `json:"caption"`
	Ordinal   int64   `json:"ordinal"`
	AddedAt   int64   `json:"added_at"`
}

type Series struct {
	ID                  int64   `json:"id"`
	Uuid                string  `json:"uuid"`
	Title               string  `json:"title"`
	FeedTitle           *string `json:"feed_title"`
	AltTitles           *string `json:"alt_titles"`
	SeasonNumber        int64   `json:"season_number"`
	Subscribed          int64   `json:"subscribed"`
	Favorite            int64   `json:"favorite"`
	AiringStatus        *string `json:"airing_status"`
	PosterPath          *string `json:"poster_path"`
	PosterPortrait      int64   `json:"poster_portrait"`
	DefaultProfileID    *int64  `json:"default_profile_id"`
	AnilistID           *int64  `json:"anilist_id"`
	MalID               *int64  `json:"mal_id"`
	RomajiTitle         *string `json:"romaji_title"`
	EnglishTitle        *string `json:"english_title"`
	Format              *string `json:"format"`
	Status              *string `json:"status"`
	EpisodeCount        *int64  `json:"episode_count"`
	Synonyms            *string `json:"synonyms"`
	CoverImageUrl       *string `json:"cover_image_url"`
	BannerImageUrl      *string `json:"banner_image_url"`
	Season              *string `json:"season"`
	SeasonYear          *int64  `json:"season_year"`
	AddedAt             int64   `json:"added_at"`
	ModifiedAt          int64   `json:"modified_at"`
	CoverColor          *string `json:"cover_color"`
	MetadataRefreshedAt *int64  `json:"metadata_refreshed_at"`
	UserStatus          *string `json:"user_status"`
	WatchStatus         string  `json:"watch_status"`
}

type Setting struct {
	ID                  int64   `json:"id"`
	DownloadRoot        string  `json:"download_root"`
	EncodedRoot         string  `json:"encoded_root"`
	CleanupPolicy       string  `json:"cleanup_policy"`
	ProcessedDir        *string `json:"processed_dir"`
	NamingTemplate      string  `json:"naming_template"`
	DownloadBackend     *int64  `json:"download_backend"`
	DefaultProfileID    *int64  `json:"default_profile_id"`
	ConcurrencyDownload int64   `json:"concurrency_download"`
	ConcurrencyEncode   int64   `json:"concurrency_encode"`
	FfmpegPath          *string `json:"ffmpeg_path"`
	YtdlpPath           *string `json:"ytdlp_path"`
	Port                int64   `json:"port"`
	DohEnabled          int64   `json:"doh_enabled"`
	AddedAt             int64   `json:"added_at"`
	ModifiedAt          int64   `json:"modified_at"`
	SetupCompleted      int64   `json:"setup_completed"`
	ShowNsfw            int64   `json:"show_nsfw"`
}
