// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	// ClearDefaultDownloadClients resets all defaults before setting a new one.
	ClearDefaultDownloadClients(ctx context.Context) error
	ClearEpisodeError(ctx context.Context, id int64) error
	CountEpisodesBySeries(ctx context.Context, seriesID int64) (int64, error)
	// CountErroredOutputs reports failed outputs for an episode; >0 keeps the original.
	CountErroredOutputs(ctx context.Context, episodeID int64) (int64, error)
	// CountUnarchivedOutputs reports how many of an episode's outputs are not yet
	// archived; 0 means the episode is fully archived (cleanup trigger).
	CountUnarchivedOutputs(ctx context.Context, episodeID int64) (int64, error)
	CreateDownloadClient(ctx context.Context, arg CreateDownloadClientParams) (DownloadClient, error)
	CreateEncodeProfile(ctx context.Context, arg CreateEncodeProfileParams) (EncodeProfile, error)
	CreateEncodedOutput(ctx context.Context, arg CreateEncodedOutputParams) (EncodedOutput, error)
	CreateEpisode(ctx context.Context, arg CreateEpisodeParams) (Episode, error)
	CreateExtension(ctx context.Context, arg CreateExtensionParams) (Extension, error)
	CreateExtensionRepo(ctx context.Context, arg CreateExtensionRepoParams) (ExtensionRepo, error)
	CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error)
	CreateScreenshot(ctx context.Context, arg CreateScreenshotParams) (Screenshot, error)
	CreateSeries(ctx context.Context, arg CreateSeriesParams) (Series, error)
	DeleteAnilistDetailCache(ctx context.Context, anilistID int64) error
	DeleteDownloadClient(ctx context.Context, id int64) error
	DeleteEncodeProfile(ctx context.Context, id int64) error
	DeleteEncodedOutput(ctx context.Context, id int64) error
	DeleteEpisode(ctx context.Context, id int64) error
	DeleteExtension(ctx context.Context, id int64) error
	DeleteExtensionRepo(ctx context.Context, id int64) error
	DeleteFeed(ctx context.Context, id int64) error
	DeleteScreenshot(ctx context.Context, id int64) error
	DeleteScreenshotsByEpisode(ctx context.Context, episodeID int64) error
	DeleteSeries(ctx context.Context, id int64) error
	GetAnilistDetailCache(ctx context.Context, anilistID int64) (AnilistDetailCache, error)
	GetDefaultDownloadClient(ctx context.Context) (DownloadClient, error)
	GetDownloadClient(ctx context.Context, id int64) (DownloadClient, error)
	GetEncodeProfile(ctx context.Context, id int64) (EncodeProfile, error)
	GetEncodeProfileByName(ctx context.Context, name string) (EncodeProfile, error)
	GetEncodeProfileByUUID(ctx context.Context, uuid string) (EncodeProfile, error)
	GetEncodedOutput(ctx context.Context, id int64) (EncodedOutput, error)
	GetEpisode(ctx context.Context, id int64) (Episode, error)
	GetEpisodeByUUID(ctx context.Context, uuid string) (Episode, error)
	// GetEpisodeWithSeries returns an episode joined with its series title so the
	// detail/queue DTOs can show the series name without a second query.
	GetEpisodeWithSeries(ctx context.Context, id int64) (GetEpisodeWithSeriesRow, error)
	GetExtension(ctx context.Context, id int64) (Extension, error)
	GetExtensionByExtID(ctx context.Context, extID string) (Extension, error)
	GetExtensionRepo(ctx context.Context, id int64) (ExtensionRepo, error)
	GetExtensionRepoByURL(ctx context.Context, url string) (ExtensionRepo, error)
	GetFeed(ctx context.Context, id int64) (Feed, error)
	GetFeedByURL(ctx context.Context, url string) (Feed, error)
	GetScreenshot(ctx context.Context, id int64) (Screenshot, error)
	GetSeries(ctx context.Context, id int64) (Series, error)
	GetSeriesByAnilistID(ctx context.Context, anilistID *int64) (Series, error)
	GetSeriesByTitle(ctx context.Context, title string) (Series, error)
	GetSeriesByUUID(ctx context.Context, uuid string) (Series, error)
	GetSettings(ctx context.Context) (Setting, error)
	IncrementEpisodeRetry(ctx context.Context, id int64) error
	InsertSettings(ctx context.Context, arg InsertSettingsParams) (Setting, error)
	ListBuiltinEncodeProfiles(ctx context.Context) ([]EncodeProfile, error)
	ListDownloadClients(ctx context.Context) ([]DownloadClient, error)
	ListEnabledDownloadClients(ctx context.Context) ([]DownloadClient, error)
	ListEnabledExtensionRepos(ctx context.Context) ([]ExtensionRepo, error)
	ListEnabledExtensionsByType(ctx context.Context, type_ string) ([]Extension, error)
	ListEncodeProfiles(ctx context.Context) ([]EncodeProfile, error)
	ListEncodedOutputsByEpisode(ctx context.Context, episodeID int64) ([]EncodedOutput, error)
	ListEncodedOutputsByStatus(ctx context.Context, status string) ([]EncodedOutput, error)
	ListEpisodesBySeries(ctx context.Context, seriesID int64) ([]Episode, error)
	ListEpisodesByStatus(ctx context.Context, status string) ([]Episode, error)
	ListExtensionRepos(ctx context.Context) ([]ExtensionRepo, error)
	ListExtensions(ctx context.Context) ([]Extension, error)
	ListExtensionsByRepo(ctx context.Context, repoID *int64) ([]Extension, error)
	ListFavoriteSeries(ctx context.Context) ([]Series, error)
	ListFeeds(ctx context.Context) ([]Feed, error)
	ListFeedsBySeries(ctx context.Context, seriesID int64) ([]Feed, error)
	// ListFeedsDueForPoll returns enabled feeds whose series is subscribed, is in the
	// 'watching' watch status (on_hold/dropped series are skipped so background
	// automation never overrides a manual choice), whose derived status still permits
	// polling (not completed/cancelled/not_aired), and whose interval has elapsed. The
	// completed/up_to_date split is computed in Go from airing_status + archive counts;
	// this query enforces the cheap, durable filters.
	ListFeedsDueForPoll(ctx context.Context, now *int64) ([]Feed, error)
	ListQueuedEpisodes(ctx context.Context) ([]Episode, error)
	ListScreenshotsByEpisode(ctx context.Context, episodeID int64) ([]Screenshot, error)
	ListScreenshotsBySeries(ctx context.Context, seriesID int64) ([]Screenshot, error)
	ListSeries(ctx context.Context) ([]Series, error)
	// ListSeriesForMetadataRefresh returns subscribed, non-finished series whose
	// AniList metadata is stale (never refreshed, or older than the cutoff). NULLs
	// sort first on ASC, so never-refreshed series are picked up before stale ones.
	ListSeriesForMetadataRefresh(ctx context.Context, arg ListSeriesForMetadataRefreshParams) ([]Series, error)
	// ListSeriesWithProgress joins archived-episode counts for the Library grid and
	// derived-status computation (archived = every selected output archived).
	ListSeriesWithProgress(ctx context.Context) ([]ListSeriesWithProgressRow, error)
	ListSubscribedSeries(ctx context.Context) ([]Series, error)
	MarkEncodedOutputArchived(ctx context.Context, id int64) error
	MarkEncodedOutputEncoded(ctx context.Context, arg MarkEncodedOutputEncodedParams) error
	MarkEpisodeArchived(ctx context.Context, id int64) error
	MarkEpisodeDownloaded(ctx context.Context, arg MarkEpisodeDownloadedParams) error
	MarkEpisodeDownloading(ctx context.Context, id int64) error
	MarkEpisodeEncoded(ctx context.Context, id int64) error
	MarkEpisodeEncoding(ctx context.Context, arg MarkEpisodeEncodingParams) error
	// MarkEpisodeSourceCleaned stamps the unix time the source files were deleted
	// under cleanup_policy=delete, so the UI can show "source cleaned up".
	MarkEpisodeSourceCleaned(ctx context.Context, arg MarkEpisodeSourceCleanedParams) error
	MarkExtensionRepoSynced(ctx context.Context, id int64) error
	MarkFeedChecked(ctx context.Context, arg MarkFeedCheckedParams) error
	MarkFeedError(ctx context.Context, arg MarkFeedErrorParams) error
	// Crash recovery: orphaned in-flight statuses reset to the last durable state.
	ResetOrphanedDownloadingEpisodes(ctx context.Context) error
	// Crash recovery: in-flight encode/thumbnail work resets to queued.
	ResetOrphanedEncodedOutputs(ctx context.Context) error
	ResetOrphanedEncodingEpisodes(ctx context.Context) error
	// ResolveProfileChain walks parent_id from the given profile to the root,
	// ordered child-first; Go COALESCEs each knob field across the chain.
	ResolveProfileChain(ctx context.Context, id int64) ([]ResolveProfileChainRow, error)
	SetDefaultDownloadClient(ctx context.Context, id int64) error
	SetDefaultProfile(ctx context.Context, defaultProfileID *int64) error
	SetDownloadBackend(ctx context.Context, downloadBackend *int64) error
	SetEncodedOutputError(ctx context.Context, arg SetEncodedOutputErrorParams) error
	// SetEncodedOutputSnapshot records the resolved x265 args used for an output
	// (reproducibility), set once the arg builder has produced them.
	SetEncodedOutputSnapshot(ctx context.Context, arg SetEncodedOutputSnapshotParams) error
	SetEncodedOutputStatus(ctx context.Context, arg SetEncodedOutputStatusParams) error
	SetEpisodeError(ctx context.Context, arg SetEpisodeErrorParams) error
	// SetEpisodeSourcePath updates source_path after the original is moved/cleaned up
	// so the row points at the new location (move) or NULL (delete).
	SetEpisodeSourcePath(ctx context.Context, arg SetEpisodeSourcePathParams) error
	SetEpisodeStatus(ctx context.Context, arg SetEpisodeStatusParams) error
	SetExtensionEnabled(ctx context.Context, arg SetExtensionEnabledParams) error
	SetExtensionRepoEnabled(ctx context.Context, arg SetExtensionRepoEnabledParams) error
	SetFeedEnabled(ctx context.Context, arg SetFeedEnabledParams) error
	SetSeriesAiringStatus(ctx context.Context, arg SetSeriesAiringStatusParams) error
	SetSeriesFavorite(ctx context.Context, arg SetSeriesFavoriteParams) error
	SetSeriesSubscribed(ctx context.Context, arg SetSeriesSubscribedParams) error
	// SetSeriesWatchStatus sets the watch status that solely drives polling: 'watching'
	// (polled), 'on_hold'/'dropped' (never polled). 'completed' is never stored here.
	SetSeriesWatchStatus(ctx context.Context, arg SetSeriesWatchStatusParams) error
	SettingsExist(ctx context.Context) (bool, error)
	UpdateDownloadClient(ctx context.Context, arg UpdateDownloadClientParams) (DownloadClient, error)
	UpdateEncodeProfile(ctx context.Context, arg UpdateEncodeProfileParams) (EncodeProfile, error)
	UpdateExtensionHealth(ctx context.Context, arg UpdateExtensionHealthParams) error
	UpdateExtensionSettings(ctx context.Context, arg UpdateExtensionSettingsParams) error
	UpdateFeed(ctx context.Context, arg UpdateFeedParams) (Feed, error)
	UpdateSeries(ctx context.Context, arg UpdateSeriesParams) (Series, error)
	// UpdateSeriesMetadata refreshes the volatile AniList-derived columns for one
	// series, preserving user/display fields (title, subscribed, favorite,
	// season_number, default_profile_id, feed_title are never touched). Authoritative
	// scalars (status/airing_status/episode_count/format/season/season_year) are set
	// directly; images, colour, titles and synonyms use COALESCE(NULLIF(@x, ''), col)
	// so a sparse response never blanks a previously-populated column.
	UpdateSeriesMetadata(ctx context.Context, arg UpdateSeriesMetadataParams) error
	UpdateSettings(ctx context.Context, arg UpdateSettingsParams) (Setting, error)
	UpsertAnilistDetailCache(ctx context.Context, arg UpsertAnilistDetailCacheParams) error
	UpsertExtensionByExtID(ctx context.Context, arg UpsertExtensionByExtIDParams) (Extension, error)
}

var _ Querier = (*Queries)(nil)
