// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: screenshots.sql

package store

import (
	"context"
)

const createScreenshot = `-- name: CreateScreenshot :one
INSERT INTO screenshots (
    uuid, episode_id, series_id, path, caption, ordinal
) VALUES (
    ?, ?, ?, ?, ?, ?
)
RETURNING id, uuid, episode_id, series_id, path, caption, ordinal, added_at
`

type CreateScreenshotParams struct {
	Uuid      string  `json:"uuid"`
	EpisodeID int64   `json:"episode_id"`
	SeriesID  int64   `json:"series_id"`
	Path      string  `json:"path"`
	Caption   *string `json:"caption"`
	Ordinal   int64   `json:"ordinal"`
}

func (q *Queries) CreateScreenshot(ctx context.Context, arg CreateScreenshotParams) (Screenshot, error) {
	row := q.db.QueryRowContext(ctx, createScreenshot,
		arg.Uuid,
		arg.EpisodeID,
		arg.SeriesID,
		arg.Path,
		arg.Caption,
		arg.Ordinal,
	)
	var i Screenshot
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.EpisodeID,
		&i.SeriesID,
		&i.Path,
		&i.Caption,
		&i.Ordinal,
		&i.AddedAt,
	)
	return i, err
}

const deleteScreenshot = `-- name: DeleteScreenshot :exec
DELETE FROM screenshots WHERE id = ?
`

func (q *Queries) DeleteScreenshot(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteScreenshot, id)
	return err
}

const deleteScreenshotsByEpisode = `-- name: DeleteScreenshotsByEpisode :exec
DELETE FROM screenshots WHERE episode_id = ?
`

func (q *Queries) DeleteScreenshotsByEpisode(ctx context.Context, episodeID int64) error {
	_, err := q.db.ExecContext(ctx, deleteScreenshotsByEpisode, episodeID)
	return err
}

const getScreenshot = `-- name: GetScreenshot :one
SELECT id, uuid, episode_id, series_id, path, caption, ordinal, added_at FROM screenshots WHERE id = ?
`

func (q *Queries) GetScreenshot(ctx context.Context, id int64) (Screenshot, error) {
	row := q.db.QueryRowContext(ctx, getScreenshot, id)
	var i Screenshot
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.EpisodeID,
		&i.SeriesID,
		&i.Path,
		&i.Caption,
		&i.Ordinal,
		&i.AddedAt,
	)
	return i, err
}

const listScreenshotsByEpisode = `-- name: ListScreenshotsByEpisode :many
SELECT id, uuid, episode_id, series_id, path, caption, ordinal, added_at FROM screenshots WHERE episode_id = ? ORDER BY ordinal ASC
`

func (q *Queries) ListScreenshotsByEpisode(ctx context.Context, episodeID int64) ([]Screenshot, error) {
	rows, err := q.db.QueryContext(ctx, listScreenshotsByEpisode, episodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Screenshot
	for rows.Next() {
		var i Screenshot
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.EpisodeID,
			&i.SeriesID,
			&i.Path,
			&i.Caption,
			&i.Ordinal,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScreenshotsBySeries = `-- name: ListScreenshotsBySeries :many
SELECT id, uuid, episode_id, series_id, path, caption, ordinal, added_at FROM screenshots WHERE series_id = ? ORDER BY episode_id ASC, ordinal ASC
`

func (q *Queries) ListScreenshotsBySeries(ctx context.Context, seriesID int64) ([]Screenshot, error) {
	rows, err := q.db.QueryContext(ctx, listScreenshotsBySeries, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Screenshot
	for rows.Next() {
		var i Screenshot
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.EpisodeID,
			&i.SeriesID,
			&i.Path,
			&i.Caption,
			&i.Ordinal,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
