// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package store

import (
	"context"
)

const getSettings = `-- name: GetSettings :one
SELECT id, download_root, encoded_root, cleanup_policy, processed_dir, naming_template, download_backend, default_profile_id, concurrency_download, concurrency_encode, ffmpeg_path, ytdlp_path, port, doh_enabled, added_at, modified_at FROM settings WHERE id = 1
`

func (q *Queries) GetSettings(ctx context.Context) (Setting, error) {
	row := q.db.QueryRowContext(ctx, getSettings)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.DownloadRoot,
		&i.EncodedRoot,
		&i.CleanupPolicy,
		&i.ProcessedDir,
		&i.NamingTemplate,
		&i.DownloadBackend,
		&i.DefaultProfileID,
		&i.ConcurrencyDownload,
		&i.ConcurrencyEncode,
		&i.FfmpegPath,
		&i.YtdlpPath,
		&i.Port,
		&i.DohEnabled,
		&i.AddedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const insertSettings = `-- name: InsertSettings :one
INSERT INTO settings (
    id, download_root, encoded_root, cleanup_policy, processed_dir,
    naming_template, download_backend, default_profile_id,
    concurrency_download, concurrency_encode, ffmpeg_path, ytdlp_path,
    port, doh_enabled
) VALUES (
    1, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, download_root, encoded_root, cleanup_policy, processed_dir, naming_template, download_backend, default_profile_id, concurrency_download, concurrency_encode, ffmpeg_path, ytdlp_path, port, doh_enabled, added_at, modified_at
`

type InsertSettingsParams struct {
	DownloadRoot        string  `json:"download_root"`
	EncodedRoot         string  `json:"encoded_root"`
	CleanupPolicy       string  `json:"cleanup_policy"`
	ProcessedDir        *string `json:"processed_dir"`
	NamingTemplate      string  `json:"naming_template"`
	DownloadBackend     *int64  `json:"download_backend"`
	DefaultProfileID    *int64  `json:"default_profile_id"`
	ConcurrencyDownload int64   `json:"concurrency_download"`
	ConcurrencyEncode   int64   `json:"concurrency_encode"`
	FfmpegPath          *string `json:"ffmpeg_path"`
	YtdlpPath           *string `json:"ytdlp_path"`
	Port                int64   `json:"port"`
	DohEnabled          int64   `json:"doh_enabled"`
}

func (q *Queries) InsertSettings(ctx context.Context, arg InsertSettingsParams) (Setting, error) {
	row := q.db.QueryRowContext(ctx, insertSettings,
		arg.DownloadRoot,
		arg.EncodedRoot,
		arg.CleanupPolicy,
		arg.ProcessedDir,
		arg.NamingTemplate,
		arg.DownloadBackend,
		arg.DefaultProfileID,
		arg.ConcurrencyDownload,
		arg.ConcurrencyEncode,
		arg.FfmpegPath,
		arg.YtdlpPath,
		arg.Port,
		arg.DohEnabled,
	)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.DownloadRoot,
		&i.EncodedRoot,
		&i.CleanupPolicy,
		&i.ProcessedDir,
		&i.NamingTemplate,
		&i.DownloadBackend,
		&i.DefaultProfileID,
		&i.ConcurrencyDownload,
		&i.ConcurrencyEncode,
		&i.FfmpegPath,
		&i.YtdlpPath,
		&i.Port,
		&i.DohEnabled,
		&i.AddedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const setDefaultProfile = `-- name: SetDefaultProfile :exec
UPDATE settings SET default_profile_id = ?, modified_at = unixepoch() WHERE id = 1
`

func (q *Queries) SetDefaultProfile(ctx context.Context, defaultProfileID *int64) error {
	_, err := q.db.ExecContext(ctx, setDefaultProfile, defaultProfileID)
	return err
}

const setDownloadBackend = `-- name: SetDownloadBackend :exec
UPDATE settings SET download_backend = ?, modified_at = unixepoch() WHERE id = 1
`

func (q *Queries) SetDownloadBackend(ctx context.Context, downloadBackend *int64) error {
	_, err := q.db.ExecContext(ctx, setDownloadBackend, downloadBackend)
	return err
}

const settingsExist = `-- name: SettingsExist :one
SELECT EXISTS (SELECT 1 FROM settings WHERE id = 1) AS present
`

func (q *Queries) SettingsExist(ctx context.Context) (bool, error) {
	row := q.db.QueryRowContext(ctx, settingsExist)
	var present bool
	err := row.Scan(&present)
	return present, err
}

const updateSettings = `-- name: UpdateSettings :one
UPDATE settings SET
    download_root = ?, encoded_root = ?, cleanup_policy = ?, processed_dir = ?,
    naming_template = ?, download_backend = ?, default_profile_id = ?,
    concurrency_download = ?, concurrency_encode = ?, ffmpeg_path = ?,
    ytdlp_path = ?, port = ?, doh_enabled = ?, modified_at = unixepoch()
WHERE id = 1
RETURNING id, download_root, encoded_root, cleanup_policy, processed_dir, naming_template, download_backend, default_profile_id, concurrency_download, concurrency_encode, ffmpeg_path, ytdlp_path, port, doh_enabled, added_at, modified_at
`

type UpdateSettingsParams struct {
	DownloadRoot        string  `json:"download_root"`
	EncodedRoot         string  `json:"encoded_root"`
	CleanupPolicy       string  `json:"cleanup_policy"`
	ProcessedDir        *string `json:"processed_dir"`
	NamingTemplate      string  `json:"naming_template"`
	DownloadBackend     *int64  `json:"download_backend"`
	DefaultProfileID    *int64  `json:"default_profile_id"`
	ConcurrencyDownload int64   `json:"concurrency_download"`
	ConcurrencyEncode   int64   `json:"concurrency_encode"`
	FfmpegPath          *string `json:"ffmpeg_path"`
	YtdlpPath           *string `json:"ytdlp_path"`
	Port                int64   `json:"port"`
	DohEnabled          int64   `json:"doh_enabled"`
}

func (q *Queries) UpdateSettings(ctx context.Context, arg UpdateSettingsParams) (Setting, error) {
	row := q.db.QueryRowContext(ctx, updateSettings,
		arg.DownloadRoot,
		arg.EncodedRoot,
		arg.CleanupPolicy,
		arg.ProcessedDir,
		arg.NamingTemplate,
		arg.DownloadBackend,
		arg.DefaultProfileID,
		arg.ConcurrencyDownload,
		arg.ConcurrencyEncode,
		arg.FfmpegPath,
		arg.YtdlpPath,
		arg.Port,
		arg.DohEnabled,
	)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.DownloadRoot,
		&i.EncodedRoot,
		&i.CleanupPolicy,
		&i.ProcessedDir,
		&i.NamingTemplate,
		&i.DownloadBackend,
		&i.DefaultProfileID,
		&i.ConcurrencyDownload,
		&i.ConcurrencyEncode,
		&i.FfmpegPath,
		&i.YtdlpPath,
		&i.Port,
		&i.DohEnabled,
		&i.AddedAt,
		&i.ModifiedAt,
	)
	return i, err
}
