// Package store owns the SQLite database lifecycle: schema migrations, the
// dual read/write connection-pool concurrency model, crash recovery, and the
// idempotent seed data the rest of the app boots against. The type-safe query
// layer in this package is generated by sqlc from db/queries + db/migrations.
package store

import (
	"context"
	"database/sql"
	"fmt"
	"net/url"
	"path/filepath"

	"github.com/google/uuid"
	"github.com/pressly/goose/v3"
	_ "modernc.org/sqlite" // cgo-free SQLite driver, registered as "sqlite"

	"github.com/modbender/ssanime-gui/db/migrations"
	"github.com/modbender/ssanime-gui/internal/config"
)

// Store wires the two connection pools (single-writer + concurrent readers) on
// one WAL database file, plus a *Queries bound to each. SQLite is single-writer;
// serializing writes through a one-connection pool removes "database is locked"
// contention while readers run concurrently under WAL.
type Store struct {
	writeDB *sql.DB
	readDB  *sql.DB

	write *Queries
	read  *Queries

	path string
}

// readPoolSize is the max concurrent reader connections. Readers never block
// each other under WAL; this only caps simultaneous open read handles.
const readPoolSize = 8

// Open resolves the DB path from cfg, opens the write and read pools with the
// correct pragmas, runs migrations, performs crash recovery, and seeds the
// immutable defaults. The returned Store must be closed by the caller.
func Open(ctx context.Context, cfg *config.Config) (*Store, error) {
	writeDB, err := openPool(cfg.DBPath, true)
	if err != nil {
		return nil, fmt.Errorf("open write pool: %w", err)
	}
	writeDB.SetMaxOpenConns(1) // serialize all writes through a single connection

	readDB, err := openPool(cfg.DBPath, false)
	if err != nil {
		_ = writeDB.Close()
		return nil, fmt.Errorf("open read pool: %w", err)
	}
	readDB.SetMaxOpenConns(readPoolSize)

	s := &Store{
		writeDB: writeDB,
		readDB:  readDB,
		write:   New(writeDB),
		read:    New(readDB),
		path:    cfg.DBPath,
	}

	if err := s.migrate(ctx); err != nil {
		_ = s.Close()
		return nil, fmt.Errorf("migrate: %w", err)
	}
	if err := s.recoverOrphaned(ctx); err != nil {
		_ = s.Close()
		return nil, fmt.Errorf("crash recovery: %w", err)
	}
	if err := s.seed(ctx, cfg); err != nil {
		_ = s.Close()
		return nil, fmt.Errorf("seed: %w", err)
	}
	return s, nil
}

// openPool opens a connection pool with WAL pragmas applied via the DSN. The
// write pool adds _txlock=immediate so writing transactions take the write lock
// up front and never deadlock on a read->write lock upgrade.
func openPool(dbPath string, write bool) (*sql.DB, error) {
	// modernc.org/sqlite reads pragmas from the DSN as repeated _pragma= keys.
	q := url.Values{}
	q.Add("_pragma", "journal_mode(WAL)")
	q.Add("_pragma", "busy_timeout(5000)")
	q.Add("_pragma", "foreign_keys(ON)")
	q.Add("_pragma", "synchronous(NORMAL)")
	if write {
		q.Set("_txlock", "immediate")
	}
	dsn := "file:" + filepath.ToSlash(dbPath) + "?" + q.Encode()
	return sql.Open("sqlite", dsn)
}

// migrate runs all pending goose migrations from the embedded migrations FS
// against the write pool.
func (s *Store) migrate(ctx context.Context) error {
	goose.SetBaseFS(migrations.FS)
	goose.SetLogger(goose.NopLogger())
	if err := goose.SetDialect("sqlite3"); err != nil {
		return err
	}
	return goose.UpContext(ctx, s.writeDB, ".")
}

// recoverOrphaned resets rows left mid-flight by a crash to their last durable
// state, per the Seanime pattern: an in-memory worker owned them, so on boot
// nothing is processing them. episodes downloading->queued, encoding->downloaded;
// encoded_outputs encoding/thumbnailing->queued.
func (s *Store) recoverOrphaned(ctx context.Context) error {
	if err := s.write.ResetOrphanedDownloadingEpisodes(ctx); err != nil {
		return err
	}
	if err := s.write.ResetOrphanedEncodingEpisodes(ctx); err != nil {
		return err
	}
	return s.write.ResetOrphanedEncodedOutputs(ctx)
}

// Read returns a *Queries bound to the concurrent read pool. Use for SELECTs.
func (s *Store) Read() *Queries { return s.read }

// Write returns a *Queries bound to the single-writer pool. Use for mutations
// that don't need a multi-statement transaction.
func (s *Store) Write() *Queries { return s.write }

// WriteTx runs fn inside an immediate write transaction on the single-writer
// pool, committing on success and rolling back on error. Use for multi-statement
// writes that must be atomic (e.g. clear-then-set-default).
func (s *Store) WriteTx(ctx context.Context, fn func(*Queries) error) error {
	tx, err := s.writeDB.BeginTx(ctx, nil)
	if err != nil {
		return err
	}
	if err := fn(s.write.WithTx(tx)); err != nil {
		_ = tx.Rollback()
		return err
	}
	return tx.Commit()
}

// WriteDB exposes the raw single-writer pool for the rare caller that needs it.
func (s *Store) WriteDB() *sql.DB { return s.writeDB }

// Close closes both pools.
func (s *Store) Close() error {
	var firstErr error
	if s.readDB != nil {
		if err := s.readDB.Close(); err != nil {
			firstErr = err
		}
	}
	if s.writeDB != nil {
		if err := s.writeDB.Close(); err != nil && firstErr == nil {
			firstErr = err
		}
	}
	return firstErr
}

// newUUID returns a random UUID string for the per-row uuid column.
func newUUID() string { return uuid.NewString() }
